import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const read = (path: string) => readFileSync(path, 'utf8')
const page = read('app/(protected)/annual-plans/page.tsx')
const grid = read('components/annual-plans/AnnualPlanGrid.tsx')
const dropzone = read('components/annual-plans/AnnualPlanUploadDropzone.tsx')
const dialog = read('components/annual-plans/AnnualPlanPreviewDialog.tsx')
const referenceFields = read('components/pr/AnnualPlanReferenceFields.tsx')
const css = read('app/globals.css')

assert.match(page, /แผนประจำปี/)
assert.match(page, /retainedFiscalYears|listAnnualPlanSlots/)
assert.match(grid, /AnnualPlanCard/)
assert.match(dropzone, /application\/pdf/)
assert.match(dropzone, /onDragEnter|onDrop/)
assert.match(dropzone, /type="file"/)
assert.match(dropzone, /role="alert"|aria-live/)
assert.match(dropzone, /fetch\(\s*['"]\/api\/annual-plans\/upload['"]\s*,/)
assert.match(dropzone, /createClient/)
assert.match(dropzone, /uploadToSignedUrl/)
assert.match(dropzone, /\/api\/annual-plans\/finalize/)
assert.match(dropzone, /JSON\.stringify/)
assert.doesNotMatch(dropzone, /const\s+formData\s*=\s*new\s+FormData/)
assert.doesNotMatch(dropzone, /body:\s*formData/)
assert.match(dialog, /iframe/)
assert.match(dialog, /ดาวน์โหลด/)
assert.match(dialog, /onCancel/)
assert.match(dialog, /annualPlanVersionFileUrl/)
assert.match(referenceFields, /AnnualPlanPreviewDialog/)
assert.match(referenceFields, /annual-plan-reference__view/)
assert.match(referenceFields, /planVersionId/)
assert.match(css, /annual-plan/)

console.log('annual plan UI: ok')
