import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const sql = readFileSync('supabase/migrations/20260826110000_annual_plan_versions_and_pr_references.sql', 'utf8')
const normalized = sql.toLowerCase()
const referenceIdHotfixSql = readFileSync('supabase/migrations/20260826151619_fix_annual_plan_reference_id_ambiguity.sql', 'utf8')
const normalizedReferenceIdHotfix = referenceIdHotfixSql.toLowerCase()
const ocrMatchingSql = readFileSync('supabase/migrations/20260903100000_fix_annual_plan_ocr_matching.sql', 'utf8')
const normalizedOcrMatchingSql = ocrMatchingSql.toLowerCase()
const manualConfirmationSql = readFileSync('supabase/migrations/20260903110000_allow_manual_annual_plan_confirmation.sql', 'utf8')
const normalizedManualConfirmationSql = manualConfirmationSql.toLowerCase()

assert.match(normalized, /create table public\.lab_stock_annual_plan_versions/)
assert.match(normalized, /create table public\.lab_stock_annual_plan_rows/)
assert.match(normalized, /alter table public\.lab_stock_annual_plans\s+add column if not exists current_version_id uuid/)
assert.match(normalized, /foreign key \(current_version_id\)[\s\S]*?references public\.lab_stock_annual_plan_versions/i)
assert.match(normalized, /unique \(annual_plan_version_id, line_number\)/)
assert.match(normalized, /purchase_request_annual_plan_references/)
assert.match(normalized, /purchase_request_annual_plan_line_references/)
assert.match(normalized, /unique \(reference_id, purchase_request_item_id\)/)
assert.match(normalized, /unique \(reference_id, plan_row_id\)/)
assert.match(normalized, /generated_by_system boolean not null default false/)
assert.match(normalized, /annual_plan_version_id uuid references public\.lab_stock_annual_plan_versions/)
assert.match(normalized, /annual_plan_reference_required boolean not null default false/)
assert.match(normalized, /sync_lab_stock_annual_plan_version_pointer/)
assert.match(normalized, /create or replace function public\.upsert_lab_stock_annual_plan_with_index/)
assert.match(normalized, /create or replace function public\.register_purchase_request_annual_plan_upload/)
assert.match(normalized, /create or replace function public\.apply_purchase_request_annual_plan_reference/)
assert.match(normalized, /create or replace function public\.create_purchase_request_with_annual_plan_checklist/)
assert.match(normalized, /create or replace function public\.update_purchase_request_with_annual_plan_checklist/)
assert.match(normalized, /new\.annual_plan_reference_required/)
assert.match(normalized, /purchase_method in \('annual_plan', 'specific_contract', 'e_bidding', 'equipment_lease'\)/, 'only methods whose checklist contains plan_page require an automatic plan reference')
assert.match(normalized, /p_request -> 'method' ->> 'kind'\) in \('annual_plan', 'specific_contract', 'e_bidding', 'equipment_lease'\)/, 'new PR wrappers must mark all plan-backed methods as reference-required')
assert.match(normalized, /plan_type text not null default 'procurement'/, 'saved references must identify procurement versus hiring source plans')
assert.match(normalized, /contract_plan_row_id uuid references public\.lab_stock_annual_plan_rows/, 'hiring references must lock the matched contract row')
assert.match(normalized, /expected_plan_type := case when target_request\.purchase_method = 'equipment_lease' then 'hiring'/, 'equipment leases must use the hiring plan')
assert.match(normalized, /contract_name_snapshot/, 'hiring references must snapshot the contract name')
assert.match(normalized, /contract_match_method not in \('name_exact', 'manual_confirmed'\)/, 'hiring references must not use an LS-code match')
assert.match(normalized, /plan_fiscal_year is distinct from current_fiscal_year/, 'the database must reject a missing or stale fiscal year')
assert.match(normalized, /contract_match_method is null/, 'the database must reject a missing hiring match method')
assert.match(normalized, /require_generated_annual_plan_attachment/, 'plan-backed PRs must reject manually uploaded plan pages at the database boundary')
assert.match(normalized, /deferrable initially deferred/)
assert.match(normalized, /enable row level security/)
assert.match(normalized, /revoke all on table public\.lab_stock_annual_plan_versions from anon, authenticated/)
assert.doesNotMatch(normalized, /created_at\s*>=\s*timestamptz\s*'2026-/)
assert.match(normalizedReferenceIdHotfix, /create or replace function public\.apply_purchase_request_annual_plan_reference/)
assert.match(normalizedReferenceIdHotfix, /v_reference_id uuid/)
assert.match(normalizedReferenceIdHotfix, /returning id into v_reference_id/)
assert.match(normalizedReferenceIdHotfix, /where reference_line\.reference_id = v_reference_id/)
assert.doesNotMatch(normalizedReferenceIdHotfix, /where reference_line\.reference_id = reference_id/)
assert.match(normalizedOcrMatchingSql, /create extension if not exists fuzzystrmatch/)
assert.match(normalizedOcrMatchingSql, /create or replace function public\.annual_plan_text_is_related/)
assert.match(normalizedOcrMatchingSql, /chr\(3659\)/, 'Thai sara-am OCR decomposition must be normalized')
assert.match(normalizedOcrMatchingSql, /extensions\.levenshtein/, 'manual confirmations must tolerate small OCR substitutions')
assert.match(normalizedOcrMatchingSql, /not public\.annual_plan_text_is_related\(contract_name, plan_row\.item_name, plan_row\.raw_text\)/)
assert.match(normalizedOcrMatchingSql, /not public\.annual_plan_text_is_related\(actual_item_name, plan_row\.item_name, plan_row\.raw_text\)/)
assert.match(normalizedManualConfirmationSql, /pg_get_functiondef\(/)
assert.match(normalizedManualConfirmationSql, /contract_match_method = 'name_exact'/)
assert.match(normalizedManualConfirmationSql, /manual confirmation is the requester's explicit row selection/)

console.log('annual plan version and PR-reference SQL contract: ok')
