import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const actor = readFileSync('lib/auth/actor.ts', 'utf8')
const admin = readFileSync('lib/supabase/admin.ts', 'utf8')
const accessDenied = readFileSync('app/(auth)/access-denied/page.tsx', 'utf8')
const login = readFileSync('app/(auth)/login/page.tsx', 'utf8')
assert.match(actor, /auth\.getUser\(\)/)
assert.match(actor, /lab_stock_memberships/)
assert.match(actor, /\.maybeSingle\(\)/)
assert.match(actor, /decideProtectedRoute\(actor\)/)
assert.match(actor, /redirect\('\/access-denied'\)/)
assert.match(readFileSync('proxy.ts', 'utf8'), /access-denied/)
assert.match(accessDenied, /LogoutButton/)
assert.doesNotMatch(accessDenied, /href="\/login"/)
assert.doesNotMatch(actor, /user_metadata/)
assert.doesNotMatch(admin, /NEXT_PUBLIC_.*SERVICE/)

const stockConfirm = readFileSync('app/auth/confirm/route.ts', 'utf8')
assert.match(stockConfirm, /type !== 'magiclink'/, 'only a portal magic-link handoff may create a stock session')
assert.match(stockConfirm, /auth\.verifyOtp\(\{ type: 'magiclink', token_hash \}\)/, 'the one-time token hash must be consumed server-side')
assert.match(stockConfirm, /NextResponse\.redirect\(new URL\('\/dashboard'/, 'a successful handoff must land on the stock dashboard')
assert.match(stockConfirm, /Cache-Control.*no-store/, 'one-time credentials must not be cached')
assert.match(stockConfirm, /Referrer-Policy.*no-referrer/, 'one-time credentials must not be forwarded as a referrer')

const proxy = readFileSync('proxy.ts', 'utf8')
assert.match(proxy, /\/auth\/confirm/, 'the one-time confirmation route must be reachable before a stock session exists')
assert.doesNotMatch(proxy, /path === '\/login'/, 'a stale session must not bounce the login page back to the dashboard')

assert.match(login, /type=\{showPassword \? 'text' : 'password'\}/)
assert.match(login, /type="button"/)
assert.match(login, /aria-pressed=\{showPassword\}/)
assert.match(login, /showPassword \? 'ซ่อนรหัสผ่าน' : 'แสดงรหัสผ่าน'/)
assert.match(login, /ระบบคลังน้ำยา<br \/>และวัสดุวิทยาศาสตร์/, 'the login panel must describe the stock system')
assert.match(login, /รับเข้า ควบคุมคงคลัง และเบิกจ่ายวัสดุอย่างเป็นระบบ/, 'the login panel must describe the current stock workflow')
assert.match(login, /รับเข้าและตรวจรับวัสดุ/, 'the login panel must lead with receiving work')
assert.match(login, /ควบคุมคงคลังและ PR/, 'the login panel must include inventory and PR work')
assert.doesNotMatch(login, /สัญญา/, 'the login panel must not describe the retired contract workflow')
