import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const page = readFileSync('app/(protected)/settings/backup/page.tsx', 'utf8')
const consoleSource = readFileSync('components/settings/BackupConsole.tsx', 'utf8')
const shell = readFileSync('components/ui/AppShell.tsx', 'utf8')
const css = readFileSync('app/globals.css', 'utf8')
const actions = readFileSync('lib/backup/actions.ts', 'utf8')
const queries = readFileSync('lib/backup/queries.ts', 'utf8')

assert.match(page, /BackupConsole/)
assert.match(page, /canManageBackups\(actor\)/)
assert.match(page, /backup-page-heading/)
assert.match(consoleSource, /requestDatabaseBackup/)
assert.match(consoleSource, /<dialog/)
assert.match(consoleSource, /aria-live="polite"/)
assert.match(consoleSource, /statusFilter/)
assert.match(consoleSource, /historyRange/)
assert.match(consoleSource, /--watch/)
assert.doesNotMatch(consoleSource, /SUPABASE_SERVICE_ROLE_KEY|BACKUP_DATABASE_URL/)
assert.match(actions, /requireActor\(\)/)
assert.match(actions, /assertBackupManager\(actor\)/)
assert.match(actions, /supabaseAdmin\.rpc\('request_lab_stock_backup'/)
assert.match(queries, /supabaseAdmin/)
assert.match(queries, /assertBackupManager/)
assert.match(shell, /href: '\/settings\/backup', label: 'สำรองฐานข้อมูล'/)
assert.match(shell, /icon: 'backup'/)
assert.match(css, /\.backup-command-panel/)
assert.match(css, /\.backup-history-cards/)
assert.match(css, /@media \(max-width: 800px\)/)
assert.match(css, /\.backup-request-dialog/)
assert.match(css, /prefers-reduced-motion/)

console.log('database backup UI contracts: ok')
