import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const read = (path: string) => readFileSync(path, 'utf8')
const compact = (value: string) => value.replace(/\s+/g, ' ')

const contractSchema = read('lib/contracts/schema.ts')
const contractTypes = read('lib/contracts/types.ts')
const contractForm = read('components/contracts/ContractForm.tsx')
const prSchema = read('lib/pr/schema.ts')
const methodFields = read('components/pr/PurchaseMethodFields.tsx')
const prReview = read('components/pr/PrReviewPanel.tsx')
const prPrint = read('components/pr/PurchaseRequestPrint.tsx')
const prDetail = read('app/(protected)/purchase-requests/[id]/page.tsx')
const contractQueries = read('lib/contracts/queries.ts')
const contractDetail = read('app/(protected)/contracts/[id]/page.tsx')
const contractSummary = read('components/contracts/ContractSummaryDialog.tsx')
const contractFilters = read('components/contracts/ContractFilters.tsx')
const contractsPage = read('app/(protected)/contracts/page.tsx')
const migration = read('supabase/migrations/20260826120000_contract_duration_years.sql')
const updateMigration = read('supabase/migrations/20260826122750_contract_update_duration_years.sql')

assert.match(contractSchema, /CONTRACT_DURATION_YEARS\s*=\s*\[1,\s*3\]\s+as const/)
assert.match(contractSchema, /contractDurationYearsSchema\s*=\s*z\.union\(\[/)
assert.match(contractSchema, /z\.literal\(CONTRACT_DURATION_YEARS\[0\]\)/)
assert.match(contractSchema, /z\.literal\(CONTRACT_DURATION_YEARS\[1\]\)/)
assert.match(contractSchema, /createContractInputSchema[\s\S]*contractDurationYears:\s*contractDurationYearsSchema/)
assert.match(contractSchema, /updateContractInputSchema[\s\S]*contractDurationYears:\s*contractDurationYearsSchema/)
assert.match(contractTypes, /contractDurationYears:\s*ContractDurationYears\s*\|\s*null/)
assert.match(contractForm, /contractDurationYears:\s*ContractDurationYears\s*\|\s*''/)
assert.match(contractForm, /id="contract-duration-years"/)
assert.match(contractForm, /CONTRACT_DURATION_YEARS\.map\(\(years\)/)
assert.match(contractForm, /aria-describedby=\{errors\.contractDurationYears/)

assert.match(prSchema, /contractDurationYears:\s*contractDurationYearsSchema\.optional\(\)/)
assert.match(prSchema, /path:\s*\['method',\s*'contractDraft',\s*'contractDurationYears'\]/)
assert.match(methodFields, /name="contractDurationYears"/)
assert.match(methodFields, /CONTRACT_DURATION_YEARS\.map\(\(years\)/)
assert.match(methodFields, /<option value=\{years\} key=\{years\}>\{years\} ปี<\/option>/)
assert.match(methodFields, /contractDurationYears:\s*1/)

assert.match(prReview, /contractDurationYears:\s*1 \| 3 \| null/)
assert.match(prReview, /จำนวนปีที่ทำสัญญ/)
assert.match(prPrint, /draft\.contractDurationYears === 1 \|\| draft\.contractDurationYears === 3/)
assert.match(prDetail, /contractDurationYears:\s*'จำนวนปีที่ทำสัญญา'/)

assert.match(contractQueries, /contract_duration_years:\s*z\.union\(\[z\.literal\(1\),\s*z\.literal\(3\)\]\)\.nullable\(\)/)
assert.match(contractQueries, /contract_duration_years,\s*\n\s*vendor/)
assert.match(contractQueries, /contractDurationYears:\s*row\.contract_duration_years/)
assert.match(contractQueries, /contractDurationYears\?:\s*\(typeof CONTRACT_DURATION_YEARS\)\[number\]/)
assert.match(contractQueries, /query\.eq\('contract_duration_years',\s*filters\.contractDurationYears\)/)

const summaryNumberPosition = contractSummary.indexOf('<dt>เลขที่สัญญา</dt>')
const summaryDurationPosition = contractSummary.indexOf('<dt>จำนวนปีที่ทำสัญญา</dt>')
assert.ok(summaryNumberPosition >= 0, 'concise contract summary must show the contract number')
assert.ok(summaryDurationPosition > summaryNumberPosition, 'duration must follow the contract number in the concise summary')
assert.match(contractDetail, /<dt>จำนวนปีที่ทำสัญญา<\/dt>/)

assert.match(contractFilters, /name="contractDurationYears"/)
assert.match(contractFilters, /<option value="">ทุกระยะเวลา<\/option>/)
assert.match(contractFilters, /<option value="1">1 ปี<\/option>/)
assert.match(contractFilters, /<option value="3">3 ปี<\/option>/)
assert.match(contractsPage, /const contractDurationYearsValue = first\(params\.contractDurationYears\)/)
assert.match(compact(contractsPage), /listContracts\(\{[^}]*contractDurationYears/)
assert.match(contractsPage, /activeParams\.set\('contractDurationYears'/)
assert.match(contractsPage, /contractDurationYears=\{contractDurationYears \? String\(contractDurationYears\) : ''\}/)

assert.match(migration, /add column if not exists contract_duration_years integer/i)
assert.match(migration, /contracts_contract_duration_years_check/i)
assert.match(migration, /check \(contract_duration_years is null or contract_duration_years in \(1, 3\)\)/i)
assert.match(migration, /create or replace function public\.enforce_purchase_request_contract_duration/i)
assert.match(migration, /before insert or update of purchase_method, method_details/i)
assert.match(migration, /create or replace function public\.copy_purchase_request_contract_duration/i)
assert.match(migration, /after update of created_contract_id/i)
assert.match(compact(migration), /set contract_duration_years = duration_text::integer where id = new\.created_contract_id/i)
assert.match(updateMigration, /add column if not exists contract_duration_years integer/i)
assert.match(updateMigration, /create or replace function public\.create_contract/i)
assert.match(updateMigration, /create or replace function public\.update_contract/i)
assert.match(updateMigration, /p_contract - 'contractDurationYears'/i)
assert.match(updateMigration, /set contract_duration_years = parsed_duration/i)
assert.doesNotMatch(updateMigration, /create table public\.lab_stock_annual_plan/i)

console.log('contract duration: ok')
