import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const read = (path: string) => readFileSync(path, 'utf8')

const contractRoutes = [
  'app/(protected)/contracts/page.tsx',
  'app/(protected)/contracts/new/page.tsx',
  'app/(protected)/contracts/[id]/page.tsx',
  'app/(protected)/contracts/[id]/edit/page.tsx',
]

for (const route of contractRoutes) {
  assert.ok(read(route).length > 0, `${route} must exist`)
}

const listPage = read(contractRoutes[0])
assert.match(listPage, /searchParams:\s*Promise</, 'Next 16 searchParams must be awaited')
assert.match(listPage, /listContracts\(/, 'contract list must read on the server')
assert.match(listPage, /ปีงบประมาณ/, 'contract list must group by fiscal year')
assert.match(listPage, /showEnded/, 'contract list must support an explicit ended-contract visibility state')
assert.match(listPage, /effectiveStatus\s*!==\s*['"]expired['"]/, 'ended contracts must stay hidden from the default register')
assert.match(listPage, /showEnded\s*\?\s*presentedContracts\.filter\(\(contract\)\s*=>\s*contract\.effectiveStatus\s*===\s*['"]expired['"]\)/, 'showing ended contracts must filter to ended contracts only')
assert.match(listPage, /แสดงสัญญาที่สิ้นสุดแล้ว/, 'users need a clear control to reveal ended contracts on demand')
assert.match(listPage, /ซ่อนสัญญาที่สิ้นสุดแล้ว/, 'the visibility control must clearly communicate its toggled state')
assert.match(listPage, /showOlder/, 'the register must support an explicit older-fiscal-year visibility state')
assert.match(listPage, /thisFiscalYear\s*-\s*4/, 'the default register must limit itself to the latest five fiscal years')
assert.match(listPage, /แสดงปีเก่าทั้งหมด/, 'users need a clear control to reveal older fiscal years')
assert.match(listPage, /ซ่อนปีเก่า/, 'the older-year control must clearly communicate its toggled state')
assert.match(listPage, /ContractFilters/, 'the register must use an interactive filter control')
assert.doesNotMatch(listPage, /แสดงผล/, 'the register filter must not require a separate apply button')

const contractFilters = read('components/contracts/ContractFilters.tsx')
assert.match(contractFilters, /^['"]use client['"]/m, 'automatic contract filtering needs a client interaction boundary')
assert.match(contractFilters, /useRouter/, 'automatic contract filtering must update the URL without a full form-submit control')
assert.match(contractFilters, /router\.replace/, 'filter changes must replace the current register URL immediately')
assert.match(contractFilters, /onChange=\{handleSelectChange\}/, 'selecting a filter must apply it immediately')
assert.match(contractFilters, /setTimeout/, 'free-text search must debounce URL updates rather than refresh on every keystroke')
assert.match(contractFilters, /aria-live="polite"/, 'automatic filter feedback must be announced accessibly')
assert.match(contractFilters, /showOlder/, 'clearing interactive filters must preserve the user\'s older-year visibility choice')

const detailPage = read(contractRoutes[2])
assert.match(detailPage, /params:\s*Promise</, 'Next 16 detail params must be awaited')
assert.match(detailPage, /StageTimeline/, 'detail must show six-step history')
assert.match(detailPage, /StageAdvanceControl/, 'detail must expose confirmed stage advance')
assert.match(detailPage, /StageTimeline contract=\{contract\} canManageStageHistory=\{canManageStageHistory\}/, 'the history timeline receives the restricted edit capability')
assert.match(detailPage, /canManageStageHistory/, 'stage history editing must be limited to stock officers and admins')
assert.match(detailPage, /contract\.procurementStage\s*===\s*['"]contract_started['"]/, 'started contracts must use a dedicated completed state')
assert.match(detailPage, /isContractStarted\s*\?\s*\(/, 'started contracts must branch to collapsed history')
assert.match(detailPage, /!isContractStarted\s*&&[\s\S]*StageAdvanceControl/, 'started contracts must not render the next action')
assert.match(detailPage, /className="route-stack contract-detail-page"/, 'contract detail must use its focused control-sheet surface')
assert.match(detailPage, /contract-detail-heading__top/, 'contract identity must keep navigation, state, and edit action together')
assert.match(detailPage, /contract-detail-heading__value/, 'contract value must be the primary summary metric')
assert.match(detailPage, /<dl className="contract-facts/, 'supporting facts must stay grouped inside the contract overview')
assert.match(detailPage, /contract-facts--vendor-split-with-value/, 'the last fact column must align under the contract value panel above it, not just sit near it')
assert.match(detailPage, /contract-facts__period[\s\S]*contract\.expiryNotice[\s\S]*contract-expiry-chip/, 'an imminent contract expiry must sit with the contract period instead of becoming a detached banner')
assert.doesNotMatch(detailPage, /contract-expiry-notice/, 'the expiry state must not consume a full-width alert row beneath the summary facts')
assert.match(detailPage, /<StatusChip tone="neutral">\{contract\.contractTypeLabel\}<\/StatusChip>/, 'contract type must be a neutral category badge, distinct from workflow status')
assert.match(detailPage, /<StatusChip tone="info">\{contract\.procurementStageLabel\}<\/StatusChip>/, 'detail must distinguish the procurement stage from contract status')
assert.match(detailPage, /\{contract\.contractStatusLabel\}/, 'detail must name the effective contract status')
assert.match(detailPage, /isAdmin\s*&&\s*isContractStarted[\s\S]*<ExpireContractDialog/, 'only admins may be offered a manual expiry action')
assert.match(detailPage, /canEdit\s*&&\s*\([\s\S]*<ContractEditDialog/, 'editors must open the real edit form from a popup')
assert.doesNotMatch(detailPage, /href=\{`\/contracts\/\$\{contract\.id\}\/edit`\}>แก้ไขข้อมูล/, 'detail must not navigate away when edit is clicked')
assert.match(detailPage, /const isAdmin = hasAppRole\(actor, ['"]admin['"]\)/, 'responsible-user management must be gated to admins')
assert.match(detailPage, /mode === ['"]budget['"] && isAdmin[\s\S]*<ResponsibleUserDialog/, 'lease admins must get the responsible-user dialog beside header actions')
assert.match(detailPage, /isAdmin\s*&&\s*\(\s*record\.isArchived/, 'only administrators may access the duplicate-or-mistake archive/restore controls')
assert.match(detailPage, /<ArchiveContractControl/, 'a live contract must still offer the archive control')
assert.match(detailPage, /<RestoreContractControl/, 'an archived contract must offer a way back instead of the archive control')

const stageHistoryEditor = read('components/contracts/StageHistoryEntryEditor.tsx')
assert.match(stageHistoryEditor, /แก้ไข/)
assert.match(stageHistoryEditor, /บันทึกย้อนหลัง/)
assert.match(stageHistoryEditor, /correctContractStageHistory/)
assert.match(stageHistoryEditor, /backfillContractStageHistory/)
const stageTimeline = read('components/contracts/StageTimeline.tsx')
assert.match(stageTimeline, /StageHistoryEntryEditor/, 'each history row owns its direct edit control')
assert.match(stageTimeline, /stage-timeline__actions/, 'row actions sit beside the corresponding history entry')

const archiveControl = read('components/contracts/ArchiveContractControl.tsx')
assert.match(archiveControl, /ลบสัญญาที่สร้างผิดหรือซ้ำ/, 'archive wording must distinguish deletion of bad data from contract expiry')
assert.match(archiveControl, /showModal\(\)/, 'deleting a bad or duplicate contract must require a deliberate modal confirmation')
assert.match(archiveControl, /aria-describedby="archive-contract-description"/, 'the destructive dialog must explain its irreversible effect')
assert.match(archiveControl, /archive-control__trigger/, 'the secondary destructive action needs its own restrained visual treatment')
assert.doesNotMatch(archiveControl, /เก็บรายการที่สร้างผิดหรือซ้ำ/, 'the old vague archive wording must not compete with the expiry action')

const budgetPanel = read('components/contracts/BudgetPanel.tsx')
assert.doesNotMatch(budgetPanel, /ResponsibleUserPicker|ผู้รับผิดชอบสัญญา/, 'responsible users must not occupy the contract detail flow')
assert.match(budgetPanel, /ExpenseMonthlyChart/, 'lease detail must show an accessible month-by-month expense bar chart')

const responsibleDialog = read('components/contracts/ResponsibleUserDialog.tsx')
assert.match(responsibleDialog, /^['"]use client['"]/m, 'responsible-user popup must be an interactive client boundary')
assert.match(responsibleDialog, /showModal\(\)/, 'admin trigger must open a modal dialog')
assert.match(responsibleDialog, /<dialog/, 'responsible-user manager must use the native accessible dialog')
assert.match(responsibleDialog, /ResponsibleUserPicker/, 'popup must preserve the real responsible-user picker')
assert.match(responsibleDialog, /key=\{pickerSession\}/, 'reopening the popup must discard unsaved local choices')
assert.match(responsibleDialog, /onSaved=\{closeDialog\}/, 'successful saving must close the popup')
assert.match(responsibleDialog, /aria-label="ปิดหน้าต่างกำหนดผู้รับผิดชอบ"/, 'popup must expose a clear close control')

const responsiblePicker = read('components/contracts/ResponsibleUserPicker.tsx')
assert.match(responsiblePicker, /onSaved\?\.\(\)/, 'responsible-user picker must notify the popup after a successful save')

const form = read('components/contracts/ContractForm.tsx')
const editDialog = read('components/contracts/ContractEditDialog.tsx')
assert.match(editDialog, /^['"]use client['"]/m, 'contract edit popup must be an interactive client boundary')
assert.match(editDialog, /showModal\(\)/, 'edit trigger must open a modal dialog')
assert.match(editDialog, /className="app-dialog app-dialog--wide"/, 'edit popup must use the centered wide-dialog surface')
assert.match(editDialog, /<ContractForm/, 'edit popup must reuse the real contract form')
assert.match(editDialog, /onCancel=\{requestClose\}/, 'form cancellation must use the popup close guard')
assert.match(editDialog, /onSaved=\{handleSaved\}/, 'successful editing must close the popup')
assert.match(editDialog, /window\.confirm/, 'closing a dirty edit popup must require confirmation')

assert.match(form, /onCancel\?:\s*\(\)\s*=>\s*void/, 'contract form must support popup cancellation')
assert.match(form, /onSaved\?:\s*\(\)\s*=>\s*void/, 'contract form must report successful modal editing')
assert.match(form, /onDirtyChange\?:\s*\(dirty:\s*boolean\)\s*=>\s*void/, 'contract form must expose dirty state to the close guard')
assert.match(form, /onSaved\?\.\(\)/, 'contract form must notify the popup after a successful edit')

const globalStyles = read('app/globals.css')
assert.match(globalStyles, /\.app-dialog\s*\{[\s\S]*position:\s*fixed;[\s\S]*inset:\s*0;[\s\S]*margin:\s*auto;/, 'application popups must stay centered in the viewport')
assert.match(
  globalStyles,
  /\.data-table tbody tr:hover \.remaining-gauge__track\s*\{[\s\S]*?border-color:\s*var\(--lab-border-strong\);[\s\S]*?\}/,
  'the remaining-quantity gauge track must gain a stronger border on row hover, so its pale background does not blend into the pale hover highlight',
)

const expenseHistory = read('components/contracts/ExpenseHistory.tsx')
assert.match(expenseHistory, /expense-history__exports/, 'CSV and Excel exports must be grouped as one coherent toolbar')
assert.match(expenseHistory, /aria-label="ดาวน์โหลดประวัติการใช้จ่าย"/, 'export actions need an accessible group label')
assert.match(expenseHistory, /const \[displayLimit, setDisplayLimit\]/, 'expense history must let users choose how many records to view')
assert.match(expenseHistory, /value=\{displayLimit\}/, 'the selected display count must remain visible')
assert.match(expenseHistory, /10 รายการ|20 รายการ|50 รายการ/, 'the display count selector must offer useful recent-record limits')
assert.match(expenseHistory, /displayedEntries\.map/, 'the table must render only the selected number of records')

const expenseForm = read('components/contracts/ExpenseForm.tsx')
assert.match(expenseForm, /expense-form__primary/, 'expense entry must group month and amount as the primary two-column decision')
assert.match(expenseForm, /expense-form__secondary/, 'record date and note must remain secondary details')
assert.match(expenseForm, /aria-invalid=\{overRemaining\}/, 'the amount field must expose an over-budget warning accessibly')
assert.match(expenseForm, /expense-form__budget-alert/, 'the remaining-budget warning needs a dedicated, findable treatment')
assert.match(expenseForm, /const \[open, setOpen\]/, 'expense entry must support an intentional show/hide state')
assert.match(expenseForm, /aria-expanded=\{open\}/, 'the show/hide control must expose its expanded state')
assert.match(expenseForm, /expense-entry__toggle/, 'expense entry needs a clear toggle control')
assert.match(expenseForm, /open && \(/, 'the expense form contents must be conditionally revealed')

const budgetGauge = read('components/contracts/BudgetGauge.tsx')
assert.match(budgetGauge, /budget-gauge__figures/, 'budget summary must retain the grouped three-figure display next to expense entry')
assert.match(budgetGauge, /budget-gauge__progress-meta/, 'budget summary must explicitly explain spent and remaining percentages beside the progress bar')
assert.match(budgetGauge, /budget-gauge__figure--used/, 'spent value needs a distinct semantic treatment')
assert.match(budgetGauge, /budget-gauge__figure--remaining-\$\{tone\}/, 'remaining value needs a semantic health treatment')
assert.match(budgetGauge, /budget-gauge__health/, 'budget summary must pair its colors with a readable health label')
assert.match(budgetGauge, /lowBudget \? 'danger'/, 'lease budget below 30% must use the danger tone')
assert.match(budgetGauge, /scaleX\(\$\{remainingPercent \/ 100\}\)/, 'detail gauge fill must show the remaining percentage')
assert.match(budgetGauge, /aria-valuenow=\{Math\.round\(remainingPercent\)\}/, 'detail gauge accessibility value must describe remaining percentage')
assert.match(budgetGauge, /aria-label="สัดส่วนงบคงเหลือ"/, 'detail gauge must label the remaining percentage')
assert.match(globalStyles, /\.budget-gauge__figure--used[\s\S]*var\(--lab-primary/, 'spent figure must use the primary information color')
assert.match(globalStyles, /\.budget-gauge__figure--remaining-ok[\s\S]*var\(--lab-green/, 'healthy remaining budget must use the success color')
assert.match(globalStyles, /\.budget-gauge__track--ok \.budget-gauge__fill[\s\S]*var\(--lab-green/, 'healthy budget progress must use the same green as the register gauge')
assert.match(globalStyles, /\.budget-gauge__track--danger \.budget-gauge__fill[\s\S]*var\(--lab-red/, 'the progress bar must turn red when exhausted')
assert.match(globalStyles, /\.expense-form__primary input,[\s\S]*border:\s*1px solid var\(--lab-border-strong\)/, 'expense entry fields must retain visible input boundaries')
assert.match(globalStyles, /\.expense-form__primary label\s*\{[\s\S]*align-content:\s*start;/, 'month and amount inputs must align at the top when amount shows a helper line')

const fileCard = read('components/contracts/ContractFileCard.tsx')
assert.match(fileCard, /contract-file-control--view/, 'an uploaded contract must expose a compact view icon')
assert.match(fileCard, /aria-label="เปิดดูไฟล์สัญญา"/, 'file view icon needs an accessible label')
assert.match(fileCard, /<dialog/, 'contract preview must open in an in-page dialog')
assert.match(fileCard, /<iframe/, 'contract preview must render inside the current page')

const historyDisclosure = read('components/contracts/StageHistoryDisclosure.tsx')
assert.match(historyDisclosure, /^['"]use client['"]/m, 'history disclosure must be an interactive client boundary')
assert.match(historyDisclosure, /aria-expanded=\{open\}/, 'history disclosure must expose its expanded state')
assert.match(historyDisclosure, /aria-controls=\{historyId\}/, 'history disclosure must connect the button to its content')
assert.match(historyDisclosure, /ดูประวัติขั้นตอนสัญญา/, 'collapsed history must have a clear Thai action label')
assert.match(historyDisclosure, /ซ่อนประวัติขั้นตอนสัญญา/, 'expanded history must have a clear Thai action label')
assert.match(historyDisclosure, /stage-history-toggle__glyph/, 'history disclosure must have a recognizable audit-trail glyph')
assert.match(historyDisclosure, /ข้อมูลย้อนหลังและวันที่มีผล/, 'history disclosure must explain what it reveals')

const expiryDialog = read('components/contracts/ExpireContractDialog.tsx')
assert.match(expiryDialog, /expireContract/, 'expiry control must persist through the dedicated Server Action')
assert.match(expiryDialog, /showModal\(\)/, 'manual expiry must require a deliberate popup confirmation')
assert.match(expiryDialog, /เหตุผลที่สิ้นสุดสัญญา/, 'manual expiry must retain a reason for audit')

assert.match(form, /^['"]use client['"]/m, 'only the interactive form is a client boundary')
assert.match(form, /createContract|updateContract/, 'form must call typed Server Actions')
assert.match(form, /state\.startImmediately\s*&&\s*item\.openingUsedQuantity\s*!=\s*null/, 'start-immediately contracts must only send a numeric opening balance when entered')
assert.doesNotMatch(form, /openingUsedQuantity:\s*item\.openingUsedQuantity\s*\?\?\s*null/, 'start-immediately contracts must not serialize an untouched opening balance as null')
assert.match(form, /localStorage/, 'form must autosave a local draft')
assert.match(form, /beforeunload/, 'form must warn before leaving an unsaved draft')
assert.doesNotMatch(form, /createBrowserClient|supabase\.from/, 'browser form must not mutate Supabase')

const itemsEditor = read('components/contracts/ContractItemsEditor.tsx')
assert.match(itemsEditor, /ยอดรวมทั้งสัญญา/, 'item editor must expose a grand total')
assert.match(itemsEditor, /item\.id/, 'edit rows must preserve stable item IDs')
assert.match(itemsEditor, /CatalogItemCombobox/, 'reagent lines must be searchable by typing, matching receiving/requisition forms')

const table = read('components/contracts/ContractTable.tsx')
const remainingGauge = read('components/contracts/ContractRemainingGauge.tsx')
const itemDisclosure = read('components/contracts/ContractItemsDisclosure.tsx')
const summaryDialog = read('components/contracts/ContractSummaryDialog.tsx')
const contractQueries = read('lib/contracts/queries.ts')
assert.match(table, /contract-table--desktop/, 'desktop table variant must exist')
assert.match(table, /contract-task-cards/, 'mobile task-card variant must exist')
assert.match(table, /contract-register-table/, 'each fiscal-year register must share one fixed table layout')
assert.match(table, /<colgroup>/, 'each fiscal-year register must declare the same column structure')
const contractNumberHeader = table.indexOf('<th>เลขที่สัญญา</th>')
const contractNameHeader = table.indexOf('<th>ชื่อสัญญา</th>')
assert.ok(contractNumberHeader >= 0 && contractNumberHeader < contractNameHeader, 'contract number must appear before contract name')
assert.match(table, /ContractRemainingGauge/, 'the register must show a remaining-balance gauge in place of contract value')
assert.match(table, /ContractSummaryDialog/, 'clicking a contract name must open a quick summary dialog')
assert.match(table, /<th[^>]*>คงเหลือ<\/th>/, 'the register must label the gauge column as remaining balance')
assert.doesNotMatch(table, /<th[^>]*>มูลค่า<\/th>/, 'the register must not keep the old contract-value column')
assert.match(remainingGauge, /aria-label=/, 'the remaining gauge must expose its percentage accessibly')
assert.match(remainingGauge, /คงเหลือ/, 'the remaining gauge must pair the color with a readable Thai label')
assert.match(remainingGauge, /remaining-gauge__fill/, 'the remaining gauge must have a dedicated visual track and fill')
assert.match(remainingGauge, /width < 30[\s\S]*tone: 'danger'/, 'remaining below 30% must use the danger tone')
assert.match(table, /ContractItemsDisclosure/, 'non-lease contracts must expose their item list from the register')
assert.match(itemDisclosure, /<details/, 'contract items must use a native show/hide disclosure')
assert.match(itemDisclosure, /รายการสินค้า/, 'the item disclosure needs a clear Thai label')
assert.match(summaryDialog, /^['"]use client['"]/m, 'the quick summary dialog must own its client interaction boundary')
assert.match(summaryDialog, /showModal()/, 'the contract name must open the native modal dialog')
assert.match(summaryDialog, /aria-haspopup="dialog"/, 'the summary trigger must announce its dialog relationship')
assert.match(summaryDialog, /ข้อมูลสัญญาแบบย่อ/, 'the dialog must identify itself as a concise contract summary')
assert.match(summaryDialog, /เปิดรายละเอียดเต็ม/, 'the summary must offer a route to the complete contract page')
assert.match(contractQueries, /contract_usage \(amount\)/, 'lease gauges must read actual contract usage entries')
assert.match(contractQueries, /contract_item_allocations \(quantity, allocation_kind\)/, 'supply gauges must read the allocation ledger and distinguish opening-balance rows')
assert.match(contractQueries, /contractRemainingPercent/, 'register balances must come from the shared contract-balance calculation')
assert.match(table, /<th>สถานะสัญญา<\/th>/, 'the register must name the contract status explicitly')
assert.match(table, /\{contract\.contractStatusLabel\}/, 'the red status chip must say expired or cancelled, not the procurement stage')
assert.match(table, /\{contract\.procurementStageLabel\}/, 'the procurement stage must remain visible separately from status')
assert.match(table, /contract-renewal-hint/, 'the register must surface an imminent renewal deadline as supporting contract metadata')
assert.doesNotMatch(table, /contract-table__status-stack/, 'the lifecycle state and renewal deadline must not be stacked in the same table cell')
assert.match(globalStyles, /\.contract-expiry-chip--danger/, 'the final-30-day deadline needs a distinct compact urgent visual treatment')
assert.match(globalStyles, /\.contract-renewal-hint--danger/, 'urgent renewal metadata needs a dedicated accessible visual treatment')
assert.match(globalStyles, /\.contract-register-table\s*\{[\s\S]*table-layout:\s*fixed/, 'fiscal-year registers must not size columns independently from their row content')

const dashboardPage = read('app/(protected)/dashboard/page.tsx')
assert.match(dashboardPage, /getExecutiveDashboard/, 'dashboard must use a real SSR\/RLS read boundary')
assert.match(dashboardPage, /รายการตามสัญญาคงเหลือต่ำ/, 'Composition C must lead with a watchlist')
assert.doesNotMatch(dashboardPage, /minimum stock/i, 'stock-ledger alert stays out until Milestone 4')

const dashboardValueCards = read('components/dashboard/ContractValueCards.tsx')
assert.match(dashboardValueCards, /มูลค่าคงเหลือในสัญญา/, 'dashboard must show remaining contract value')
assert.match(dashboardValueCards, /remainingPercent\s*<\s*30/, 'the remaining-value card must flag risk below 30%, matching the watchlist threshold')

const dashboardData = read('lib/dashboard/contracts.ts')
assert.match(dashboardData, /quantity\s*-\s*allocatedQuantity/, 'remaining quantity must use the allocation ledger')
assert.match(dashboardData, /remainingPercent\s*<\s*30/, 'watchlist threshold must be below 30%')
assert.match(dashboardData, /lifecycleStatus\s*===\s*'active'/, 'dashboard watchlists must exclude ended or cancelled contracts')
assert.match(dashboardData, /activeContracts:[\s\S]*effectiveContractStatus\(contract\.status, contract\.end_date\)/, 'active counts must use effective lifecycle status')
assert.match(dashboardData, /createClient/, 'dashboard reads must use authenticated SSR Supabase')
assert.doesNotMatch(dashboardData, /supabaseAdmin/, 'dashboard reads must stay under RLS')

console.log('contract UI and executive dashboard contract ok')
