import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'

const read = (path: string) => (existsSync(path) ? readFileSync(path, 'utf8') : '')

const migrationPath = 'supabase/migrations/20260824090000_lab_stock_line_notifications.sql'
const migration = read(migrationPath)
const config = read('lib/line/config.ts')
const client = read('lib/line/client.ts')
const message = read('lib/pr/line-notification.ts')
const actions = read('lib/pr/line-notification-actions.ts')
const queries = read('lib/pr/line-notification-queries.ts')
const types = read('lib/pr/types.ts')
const page = read('app/(protected)/purchase-requests/[id]/page.tsx')
const review = read('components/pr/PrReviewPanel.tsx')
const button = read('components/pr/PurchaseRequestLineNotifyButton.tsx')
const styles = read('app/globals.css')
const packageJson = read('package.json')
const envExample = read('.env.example')

assert.ok(existsSync(migrationPath), 'LINE notification migration must exist')
assert.match(migration, /create table if not exists public\.purchase_request_line_notifications/)
assert.match(migration, /status text not null check \(status in \('pending', 'succeeded', 'failed', 'unknown'\)\)/)
assert.match(migration, /create unique index[\s\S]*purchase_request_line_notifications_pending_idx[\s\S]*where status = 'pending'/i)
assert.match(migration, /alter table public\.purchase_request_line_notifications enable row level security/)
assert.match(migration, /revoke all on table public\.purchase_request_line_notifications from public, anon, authenticated/)
assert.match(migration, /grant select, insert, update on table public\.purchase_request_line_notifications to service_role/)
assert.match(migration, /create or replace function public\.begin_purchase_request_line_notification/)
assert.match(migration, /create or replace function public\.complete_purchase_request_line_notification/)
assert.match(migration, /security invoker[\s\S]*begin_purchase_request_line_notification/)
assert.match(migration, /po_file_path[\s\S]*po_file_deleted_at/)
assert.match(migration, /p_confirmed_attempt_id is distinct from latest_attempt\.id/)
assert.match(migration, /latest_attempt\.created_at >= now\(\) - interval '24 hours'/)
assert.match(migration, /for update/)
assert.match(migration, /perform public\.assert_stock_officer_actor\(p_actor_id\)/)
assert.match(migration, /revoke execute on function public\.begin_purchase_request_line_notification/)
assert.match(migration, /grant execute on function public\.begin_purchase_request_line_notification[^\n]*to service_role/)
assert.match(migration, /grant execute on function public\.complete_purchase_request_line_notification[^\n]*to service_role/)

assert.match(config, /LINE_CHANNEL_ACCESS_TOKEN/)
assert.match(config, /LINE_GROUP_ID/)
assert.match(config, /APP_BASE_URL/)
assert.match(client, /https:\/\/api\.line\.me\/v2\/bot\/message\/push/)
assert.match(client, /X-Line-Retry-Key/)
assert.match(client, /AbortSignal\.timeout|AbortController/)
assert.match(client, /500/)
assert.match(client, /409/)
assert.match(message, /type\s*:\s*['"]flex['"]/)
assert.match(message, /เปิดเอกสาร PO/)
assert.match(message, /documentNumber/)
assert.match(message, /poNumber/)
assert.match(message, /department/)
assert.match(message, /requesterName/)
assert.match(message, /itemCount/)
assert.match(message, /total/)

assert.match(actions, /export async function notifyPurchaseRequestInLine/)
assert.match(actions, /begin_purchase_request_line_notification/)
assert.match(actions, /complete_purchase_request_line_notification/)
assert.match(actions, /requireActor\(\)/)
assert.match(actions, /assertStockOperator/)
assert.match(actions, /revalidatePath\(`\/purchase-requests\/\$\{.*\}`\)/)
assert.match(queries, /PurchaseRequestLineNotificationSummary/)
assert.match(queries, /supabaseAdmin/)
assert.match(types, /PurchaseRequestLineNotificationSummary/)
assert.match(types, /lineNotification/)

assert.match(page, /getLatestPurchaseRequestLineNotification/)
assert.match(page, /lineNotificationConfigured/)
assert.match(review, /PurchaseRequestLineNotifyButton/)
assert.match(review, /request\.poNumber && request\.poFile\.path && !request\.poFile\.deletedAt/)
assert.match(review, /request\.poFile\.path/)
assert.match(review, /hasActivePoFile/)
assert.match(review, /showPoWorkbench/)
assert.match(button, /แจ้งใน Line/)
assert.match(button, /showModal/)
assert.match(button, /confirmedAttemptId/)
assert.match(button, /role="alert"/)
assert.match(button, /latest\?\.status === 'pending'/)
assert.match(button, /aria-haspopup="dialog"/)
assert.match(button, /decision-panel__actions line-notify-dialog__actions/)
assert.match(styles, /pr-review__po-file-heading/)
assert.match(styles, /line-notify/)
assert.match(styles, /\.line-notify-dialog__actions\s*\{[^}]*margin-top:\s*16px/)
assert.match(styles, /flex-direction: column/)

assert.match(packageJson, /test:line-notifications/)
assert.match(envExample, /LINE_CHANNEL_ACCESS_TOKEN/)
assert.match(envExample, /LINE_GROUP_ID/)
assert.match(envExample, /APP_BASE_URL/)

console.log('LINE PO notification contract: ok')
