import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const read = (path: string) => readFileSync(path, 'utf8')

const migration = read('supabase/migrations/20260820030000_lab_stock_notifications.sql')
const queries = read('lib/notifications/queries.ts')
const actions = read('lib/notifications/actions.ts')
const center = read('components/notifications/NotificationCenter.tsx')
const shell = read('components/ui/AppShell.tsx')
const layout = read('app/(protected)/layout.tsx')
const styles = read('app/globals.css')

assert.match(migration, /create table if not exists public\.lab_stock_notifications/)
assert.match(migration, /unique \(recipient_id, event_type, entity_id\)/)
assert.match(migration, /grant update \(read_at\) on table public\.lab_stock_notifications to authenticated/)
assert.match(migration, /create policy lab_stock_notifications_recipient_read/)
assert.match(migration, /using \(recipient_id = \(select auth\.uid\(\)\)\)/)
assert.match(migration, /create policy lab_stock_notifications_recipient_update/)
assert.match(migration, /create or replace function public\.enqueue_purchase_request_notification/)
assert.match(migration, /new\.status = 'pending'/)
assert.match(migration, /create or replace function public\.enqueue_requisition_notification/)
assert.match(migration, /new\.status = 'waiting'/)
assert.match(migration, /membership\.role in \('admin', 'stock_officer'\)/)
assert.match(migration, /profile\.ephis_id = '9495'/)
assert.match(migration, /create trigger purchase_requests_enqueue_notification/)
assert.match(migration, /create trigger requisitions_enqueue_notification/)
assert.match(migration, /after insert or update of status on public\.purchase_requests/)
assert.match(migration, /after insert or update of status on public\.requisitions/)
assert.match(migration, /create trigger purchase_requests_resolve_notification/)
assert.match(migration, /create trigger requisitions_resolve_notification/)
assert.match(migration, /alter publication supabase_realtime add table public\.lab_stock_notifications/)
assert.doesNotMatch(migration, /security definer/i, 'notification triggers must not expose a public security-definer function')

assert.match(queries, /canOperateStock\(actor\)/)
assert.match(queries, /\.eq\('status', 'pending'\)/)
assert.match(queries, /\.eq\('status', 'waiting'\)/)
assert.match(queries, /\.eq\('recipient_id', actor\.id\)/)
assert.match(queries, /\.is\('read_at', null\)/)
assert.match(actions, /\.eq\('id', parsedId\)/)
assert.match(actions, /\.eq\('recipient_id', actor\.id\)/)
assert.match(actions, /\.update\(\{ read_at:/)

assert.match(layout, /getNotificationSnapshot\(actor\)/)
assert.match(shell, /<NotificationCenter/)
assert.match(shell, /pendingPurchaseRequests/)
assert.match(shell, /waitingRequisitions/)
assert.match(center, /postgres_changes/)
assert.match(center, /event: 'INSERT'/)
assert.match(center, /event: 'UPDATE'/)
assert.match(center, /aria-live="polite"/)
assert.match(center, /markAllNotificationsRead/)
assert.match(styles, /\.bench-nav__count\s*\{/)
assert.match(styles, /\.notification-center__panel\s*\{/)
assert.match(styles, /\.notification-center__toast\s*\{/)

console.log('stock notification contract: ok')
