import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'

const read = (path: string) => readFileSync(path, 'utf8')
for (const path of [
  'app/(protected)/service-procurement/plans/page.tsx',
  'app/(protected)/service-procurement/plans/new/page.tsx',
  'app/(protected)/service-procurement/plans/[id]/page.tsx',
  'app/(protected)/service-procurement/purchase-requests/page.tsx',
  'app/(protected)/service-procurement/purchase-requests/new/page.tsx',
  'app/(protected)/service-procurement/purchase-requests/[id]/page.tsx',
]) assert.equal(existsSync(path), true, `${path} must exist`)

const shell = read('components/ui/AppShell.tsx')
assert.match(shell, /href: '\/service-procurement', label: 'งานจ้าง'/)
assert.match(shell, /href: '\/service-procurement\/plans', label: 'แผนงานจ้าง'/)
assert.match(shell, /href: '\/service-procurement\/purchase-requests', label: 'ใบ PR \(งานจ้าง\)'/)
assert.match(shell, /item\.href === '\/service-procurement\/purchase-requests'/, 'เมนูใบ PR งานจ้างต้องเลือกจำนวนแจ้งเตือนของตัวเอง')
assert.match(shell, /notificationState\.pendingServicePurchaseRequests/, 'เมนูใบ PR งานจ้างต้องแสดงจำนวนที่รอดำเนินการ')
assert.match(shell, /!serviceProcurementOpen \|\| collapsed/, 'เมื่อเมนูงานจ้างหุบหรือ sidebar ย่อ ต้องย้าย badge ไปที่หัวข้องานจ้าง')
assert.match(shell, /bench-nav__accordion-count/, 'หัวข้องานจ้างต้องมี badge สำรองเมื่อเมนูย่อยถูกซ่อน')
assert.match(shell, /const \[serviceProcurementOpen, setServiceProcurementOpen\]/, 'งานจ้างต้องมี state สำหรับยุบและขยายเมนูย่อย')
assert.match(shell, /className="bench-nav__accordion-trigger"/, 'หัวข้องานจ้างต้องเป็นปุ่ม accordion')
assert.match(shell, /aria-expanded=\{!collapsed && serviceProcurementOpen\}/, 'ปุ่มงานจ้างต้องประกาศสถานะเปิดให้ assistive technology')
assert.match(shell, /aria-controls="service-procurement-subnav"/, 'ปุ่มงานจ้างต้องเชื่อมกับรายการเมนูย่อย')
assert.match(shell, /setServiceProcurementOpen\(\(open\) => !open\)/, 'ปุ่มงานจ้างต้องสลับสถานะเมนูย่อยได้')
assert.match(shell, /bench-nav__accordion-chevron/, 'หัวข้องานจ้างต้องมี chevron แสดงสถานะ')
assert.match(shell, /bench-nav--nested/)
const plansPage = read('app/(protected)/service-procurement/plans/page.tsx')
const planDetail = read('app/(protected)/service-procurement/plans/[id]/page.tsx')
const globalStyles = read('app/globals.css')
const planTable = read('components/service-procurement/ServicePlanTable.tsx')
const planExpenseControls = read('components/service-procurement/ServicePlanExpenseControls.tsx')
const purchaseRequestsPage = read('app/(protected)/service-procurement/purchase-requests/page.tsx')
const purchaseRequestTable = read('components/service-procurement/ServicePurchaseRequestTable.tsx')
const purchaseRequestSummaryDialog = read('components/service-procurement/ServicePurchaseRequestSummaryDialog.tsx')
const purchaseRequestExpenseDialog = read('components/service-procurement/ServicePurchaseRequestExpenseDialog.tsx')
const purchaseRequestControls = read('components/service-procurement/ServicePurchaseRequestControls.tsx')
const serviceExpenseActions = read('lib/service-procurement/actions.ts')
const serviceQueries = read('lib/service-procurement/queries.ts')
const servicePresenter = read('lib/service-procurement/presenter.ts')
assert.match(planDetail, /service-plan-overview/, 'service plan detail must lead with a financial overview')
assert.match(planDetail, /service-plan-detail__heading-copy/, 'service plan detail heading must keep title and metadata together')
assert.match(planDetail, /service-plan-overview__status/, 'service plan balance must show a styled status indicator')
assert.match(planDetail, /aria-label="สัดส่วนยอดใช้จริงและยอดสำรอง"/, 'service plan progress must have an accessible label')
assert.match(planDetail, /formatThaiDateLong\(fiscal\.start\)/, 'service plan fiscal-year start must use the full Thai date')
assert.match(planDetail, /formatThaiDateLong\(fiscal\.end\)/, 'service plan fiscal-year end must use the full Thai date')
assert.doesNotMatch(planDetail, /ServicePlanResponsibleDialog|กำหนดผู้รับผิดชอบ/, 'service plan detail must not show the removed responsible-user action')
assert.match(globalStyles, /\.service-plan-ledger-panel > \.field-help\s*\{[\s\S]*?padding:/, 'fiscal-year helper text must stay inside the ledger panel frame')
assert.match(globalStyles, /\.service-plan-overview__stats > \.service-plan-overview__stat--available\s*\{[^}]*background: var\(--lab-green-soft\)/, 'available budget stat must use a distinct semantic surface')
assert.match(globalStyles, /\.service-plan-overview__stats > \.service-plan-overview__stat--available dd\s*\{[^}]*color: var\(--lab-green\)/, 'available budget value must use a distinct semantic color')
assert.match(planDetail, /CLOSED PO LEDGER/, 'service plan detail must show the closed PO ledger')
assert.match(planDetail, /ServicePlanExpenseControls/, 'service plan detail must expose the budget control')
assert.doesNotMatch(planDetail, /service-plan-detail-grid|service-plan-people-panel/, 'service plan detail must not reserve space for the removed team/activity panels')
assert.match(planTable, /ContractRemainingGauge/, 'service plan list must show the remaining-budget gauge')
assert.match(planTable, /plan\.balance\.available\s*\/\s*plan\.balance\.budget/, 'service plan gauge must be based on the available budget')
assert.match(planTable, /service-plan-table__gauge/, 'service plan table must reserve a readable gauge column')
assert.match(planTable, /service-plan-card__balance-gauge/, 'service plan mobile cards must show the same gauge')
assert.match(purchaseRequestTable, /service-pr-cards/, 'service PR list must keep a mobile-friendly card view')
assert.match(purchaseRequestTable, /ServicePurchaseRequestSummaryDialog/, 'service PR numbers must open a compact summary dialog')
assert.doesNotMatch(purchaseRequestTable, /ServicePurchaseRequestExpenseDialog/, 'service PR list must not show the expense action')
assert.doesNotMatch(purchaseRequestTable, /มีไฟล์แนบ PO/, 'service PR list must not show the PO attachment helper text')
assert.match(purchaseRequestTable, /DetailIconLink/, 'service PR list must expose an icon link to the full detail')
assert.match(purchaseRequestTable, /<th className="service-pr-table__action-heading">การทำงาน<\/th>/, 'service PR table must label the action column')
assert.doesNotMatch(purchaseRequestTable, /<th>ประเภทงาน<\/th>/, 'service PR table must not show the removed work-type column')
assert.doesNotMatch(purchaseRequestTable, /<td>\{serviceMethodLabel\(request\.purchaseMethod\)\}<small>\{request\.usageStartDate\}/, 'service PR table must not render work type as a desktop column')
assert.match(purchaseRequestTable, /className="service-pr-table__plan-heading"/, 'service PR table must mark the widened plan heading')
assert.match(purchaseRequestTable, /className="service-pr-table__plan-cell"/, 'service PR table must mark the widened plan cells')
assert.match(purchaseRequestTable, /service-pr-table__actions/, 'service PR row actions must share one dedicated action group')
assert.doesNotMatch(purchaseRequestTable, /<td>\{request\.poNumber \?\? '—'\}\{request\.status === 'confirmed'/, 'service PR expense action must not be embedded in the PO column')
assert.doesNotMatch(purchaseRequestTable, /servicePoStatusLabel\(request\.poStatus\)/, 'expense action must not carry the PO status label')
assert.match(purchaseRequestSummaryDialog, /useDeferredDialog/, 'service PR summary must use the shared accessible dialog pattern')
assert.match(purchaseRequestSummaryDialog, /aria-haspopup="dialog"/, 'service PR summary trigger must identify its dialog relationship')
assert.match(purchaseRequestSummaryDialog, /เปิดรายละเอียดเต็มใบ PR/, 'service PR summary must offer a full-detail escape route')
assert.match(purchaseRequestSummaryDialog, /service-pr-summary-dialog__items/, 'service PR summary must show its test items')
assert.match(purchaseRequestSummaryDialog, /formatThaiDate\(request\.usageStartDate\)/, 'service PR summary must format the PO start date like the created date')
assert.match(purchaseRequestSummaryDialog, /formatThaiDate\(request\.usageEndDate\)/, 'service PR summary must format the PO end date like the created date')
assert.match(purchaseRequestSummaryDialog, /ServicePurchaseRequestExpenseDialog/, 'service PR summary must expose the expense action')
assert.match(purchaseRequestSummaryDialog, /hasPoEvidence/, 'service PR summary expense action must be gated by PO evidence')
assert.doesNotMatch(purchaseRequestSummaryDialog, /onOpen=\{closeDialog\}/, 'opening expenses from the summary must not close the parent dialog during the same event')
assert.match(purchaseRequestExpenseDialog, /recordServiceLabExpense/, 'service PR expense popup must submit through the existing action')
assert.match(purchaseRequestExpenseDialog, /service-expense-dialog__history-list/, 'service PR expense popup must show a scrollable expense history')
assert.match(purchaseRequestExpenseDialog, /slice\(0, 5\)|max-height/, 'service PR expense popup must keep the latest five items visible')
assert.match(purchaseRequestExpenseDialog, /service-expense-dialog__history-main/, 'expense history rows must have a dedicated readable content column')
assert.match(purchaseRequestExpenseDialog, /service-expense-dialog__history-amount/, 'expense history rows must have a dedicated amount column')
assert.match(purchaseRequestExpenseDialog, /hasDuplicateServiceInvoice/, 'expense popup must validate duplicate Invoice numbers before submit')
assert.match(purchaseRequestExpenseDialog, /aria-invalid=\{Boolean\(invoiceError\)\}/, 'duplicate Invoice feedback must be connected to the input')
assert.match(purchaseRequestExpenseDialog, /createPortal/, 'expense popup must render outside the compact summary dialog layer')
assert.match(purchaseRequestExpenseDialog, /document\.body/, 'expense popup portal must mount at the document root')
assert.match(serviceExpenseActions, /isDuplicateServiceInvoiceError/, 'server actions must translate the database duplicate-Invoice error')
assert.match(serviceExpenseActions, /DUPLICATE_SERVICE_INVOICE_MESSAGE/, 'server actions must return a clear duplicate-Invoice message')
assert.doesNotMatch(purchaseRequestExpenseDialog, /Invoice <small>\(ไม่บังคับ\)/, 'expense popup Invoice label must not show optional-field copy')
assert.match(purchaseRequestControls, /service-pr-field/, 'service PO references must use grouped field rows')
assert.match(purchaseRequestControls, /service-pr-action-row--po/, 'service PO actions must use a dedicated action row')
assert.doesNotMatch(planTable, /formatServiceBalance|formatBaht\(plan\.balance\.spent\)|formatBaht\(plan\.balance\.reserved\)/, 'service plan list must not show duplicate spent/reserved balance columns')
assert.doesNotMatch(plansPage, /contractDurationYears|expiryNotice|contractSpendingRates|startDate|endDate/, 'service plan list must not monitor contract duration')
assert.doesNotMatch(planDetail, /contractDurationYears|expiryNotice|contractSpendingRates|startDate|endDate/, 'service plan detail must not monitor contract duration')
assert.match(planExpenseControls, /reviseServicePlanBudget/, 'service plan financial changes must use the budget revision action')
assert.match(planExpenseControls, /className="app-dialog service-plan-financial-dialog"/, 'financial forms must use an accessible dialog')
assert.doesNotMatch(planExpenseControls, /recordServicePlanHistoricalExpense|adjustServicePlanExpense|AUDITED ADJUSTMENT/, 'manual expense entry must stay removed from this page')
assert.doesNotMatch(planExpenseControls, /HISTORICAL ENTRY/, 'expense entry must use the updated English label')
assert.doesNotMatch(planExpenseControls, /บันทึกค่าใช้จ่ายย้อนหลัง/, 'expense entry must use the updated Thai label')
assert.match(plansPage, /AutoFilterBench/)
assert.match(purchaseRequestsPage, /AutoFilterBench/)
assert.match(plansPage, /showClear=\{false\}/)
assert.match(purchaseRequestsPage, /showClear=\{false\}/)
assert.match(purchaseRequestsPage, /name: 'department'/)
assert.match(purchaseRequestsPage, /SERVICE_REQUEST_FILTER_STATUSES/, 'ตัวกรองสถานะต้องใช้ชุดสถานะที่ย่อสำหรับผู้ใช้')
assert.match(purchaseRequestsPage, /SERVICE_REQUEST_FILTER_STATUSES\.map/, 'ตัวกรองสถานะต้องใช้ชุดสถานะที่ย่อสำหรับผู้ใช้')
assert.doesNotMatch(purchaseRequestsPage, /SERVICE_REQUEST_DISPLAY_STATUSES\.map/, 'สถานะรายละเอียดต้องไม่ถูกนำมาแสดงเป็นตัวกรองทั้งหมด')
assert.match(purchaseRequestsPage, /placeholder: 'เลข SPR \/ PO \/ PR จาก E-Phis \/ Invoice \/ รายการตรวจ \/ หน่วยงาน \/ ผู้ขอ'/, 'ค้นหาใบ PR งานจ้างต้องบอกช่องค้นหาหลักให้ครบ')
assert.match(purchaseRequestsPage, /serviceRequestDisplayStatusLabel\(value\)/, 'ตัวกรอง PR งานจ้างต้องใช้ชื่อสถานะเดียวกับที่แสดงในรายการ')
assert.match(servicePresenter, /pending_confirmation: 'รอคลังยืนยัน PR'/, 'ป้ายสถานะ PR งานจ้างต้องระบุขั้นตอนปัจจุบันให้ชัดเจน')
assert.match(serviceQueries, /filters\.department\) query = query\.eq\('department', filters\.department\)/)
assert.match(serviceQueries, /invoice_number/, 'คำค้นใบ PR งานจ้างต้องค้นจากเลข Invoice ได้')
assert.match(serviceQueries, /po_number\.ilike/, 'คำค้นใบ PR งานจ้างต้องค้นจากเลข PO ได้')
assert.match(serviceQueries, /ephis_pr_number\.ilike/, 'คำค้นใบ PR งานจ้างต้องค้นจากเลข PR จาก E-Phis ได้')
assert.match(serviceQueries, /service_purchase_request_test_item_snapshots/, 'คำค้นใบ PR งานจ้างต้องค้นจากรายการตรวจได้')
assert.match(serviceQueries, /service_purchase_request_items/, 'คำค้นใบ PR งานจ้างต้องรองรับรายการตรวจของข้อมูลเดิมได้')
assert.match(serviceQueries, /serviceRequestMatchesDisplayStatus/, 'ผลลัพธ์ต้องกรองตามสถานะ workflow ที่แสดงต่อผู้ใช้')
assert.doesNotMatch(plansPage, /กรองรายการ|ดูปีย้อนหลัง/)
assert.doesNotMatch(purchaseRequestsPage, /กรองรายการ|ดูปีย้อนหลัง/)
assert.doesNotMatch(plansPage, /service-procurement-tabs/)
assert.doesNotMatch(purchaseRequestsPage, /service-procurement-tabs/)
assert.doesNotMatch(read('app/globals.css'), /\.service-procurement-tabs/)
assert.match(read('app/globals.css'), /\.bench-nav__group--service/)
assert.match(read('app/globals.css'), /\.bench-nav__group--service:not\(\.is-open\) \.bench-nav--nested/, 'เมนูย่อยต้องถูกซ่อนเมื่อ accordion ปิด')
assert.match(read('app/globals.css'), /\.bench-nav__group--service\.is-open \.bench-nav__accordion-chevron/, 'chevron ต้องเปลี่ยนทิศเมื่อ accordion เปิด')
assert.match(read('app/globals.css'), /\.bench-nav__accordion-count/, 'badge ของหัวข้องานจ้างต้องจัดวางใน trigger ได้')
const autoFilter = read('components/ui/AutoFilterBench.tsx')
assert.match(autoFilter, /onChange=\{handleSelectChange\}/)
assert.match(autoFilter, /aria-busy=\{isPending\}/, 'ตัวกรองต้องประกาศสถานะกำลังโหลดโดยไม่เปลี่ยน layout')
assert.match(autoFilter, /visually-hidden.*กำลังกรองรายการ/, 'สถานะโหลดของตัวกรองต้องไม่เพิ่มแถวใหม่ระหว่างกรอง')
assert.doesNotMatch(autoFilter, /ตัวกรองอัปเดตอัตโนมัติ/)
assert.match(read('components/service-procurement/ServicePurchaseRequestForm.tsx'), /RED CROSS TEST ITEMS/)
assert.doesNotMatch(read('components/service-procurement/ServicePurchaseRequestControls.tsx'), /แจ้งเตือนผ่าน LINE/, 'service PR workflow must not show the LINE notification button')
assert.match(read('components/service-procurement/ServicePurchaseRequestHeaderEdit.tsx'), /แก้ไขข้อมูลก่อนคลังยืนยัน/)
const serviceForm = read('components/service-procurement/ServicePurchaseRequestForm.tsx')
assert.match(serviceForm, /ThaiDateInput/, 'service PR date must use the shared Thai date control')
assert.match(serviceForm, /bangkokIsoDate/, 'service PR date must use the Bangkok-local default')
assert.match(serviceForm, /service-pr-test-items-table/, 'service PR lines must use the service test-item table')
assert.match(serviceForm, /QuantityInput/, 'service PR lines must support formatted quantities')
assert.match(serviceForm, /calculateServiceRequestTotal/, 'service PR lines must calculate their totals')
assert.match(serviceForm, /aria-labelledby="service-header-title"/, 'service panels must expose heading relationships')
assert.match(serviceForm, /createServicePurchaseRequest\(formData\)/, 'service submit action must remain unchanged')
assert.match(serviceForm, /\/service-procurement\/purchase-requests/, 'service cancel route must remain unchanged')
assert.match(serviceForm, /CommitteeMemberCombobox/, 'service committee inputs must reuse the searchable PR committee control')
assert.match(serviceForm, /pr-checklist__dropzone/, 'service checklist uploads must reuse the PR dropzone presentation')
assert.match(serviceForm, /onDragOver(?=:|=)/, 'service checklist uploads must support drag and drop')
assert.match(serviceForm, /onDrop(?=:|=)/, 'service checklist uploads must accept dropped files')
assert.match(serviceForm, /formData\.set\('tor', tor/, 'service files must be submitted through FormData')
assert.doesNotMatch(serviceForm, /<select required value=\{committees\.find/, 'service committee inputs must not regress to native dropdowns')
assert.match(serviceForm, /disabled=\{pending \|\| !plan\}/, 'service PR submit must stay disabled until a plan is selected')
assert.match(serviceForm, /const today = bangkokIsoDate\(\)/, 'service PO dates must default to the Bangkok-local current date')
assert.match(serviceForm, /service-po-date-range form-grid__wide/, 'service PO date fields must share one row')
assert.match(serviceForm, /addIsoDays\(usageStartDate, 1\)/, 'PO end date must start after the selected start date')
assert.match(serviceForm, /usageEndDate <= usageStartDate/, 'service PO form must reject an end date equal to or before its start date')
assert.doesNotMatch(serviceForm, /ยอดรวมเกินวงเงินคงเหลือ/, 'service PR form must not show an over-budget warning')
assert.doesNotMatch(serviceForm, /if \(numericAmount > plan\.balance\.available\)/, 'editing a reserved service PR must not re-reject its existing reservation')
assert.doesNotMatch(serviceForm, /วงเงินแผนคงเหลือ/, 'service PR form must not show the stale remaining-budget error')
const picker = read('components/pr/ContractItemPicker.tsx')
assert.match(picker, /variant\?: 'inventory' \| 'service'/, 'shared picker must expose a service presentation variant')
assert.match(picker, /manualUnitPrice\?: boolean/, 'service manual items must optionally collect a unit price')
const styles = read('app/globals.css')
assert.match(styles, /\.service-pr-form/, 'service form needs an explicit layout wrapper')
assert.match(styles, /\.service-pr-field/, 'service PO reference fields need an explicit layout')
assert.match(styles, /\.service-pr-cards/, 'service PR list needs a mobile card layout')
assert.match(styles, /\.service-pr-table__action-cell/, 'service PR list needs a dedicated full-detail action column')
assert.match(styles, /\.service-pr-table__plan-heading\s*,\s*\.service-pr-table__plan-cell\s*\{[^}]*width:\s*24%/, 'service PR list needs a wider plan column')
assert.match(styles, /\.service-expense-dialog__history-list/, 'service PR expense history needs a bounded scroll region')
assert.match(styles, /\.service-expense-dialog\s*\{[^}]*text-align:\s*left/, 'expense popup must reset inherited table alignment')
assert.match(styles, /\.service-expense-dialog__history-amount/, 'expense history needs an aligned amount treatment')
assert.match(styles, /\.service-pr-summary-dialog \.list-summary-dialog__footer\s*\{[^}]*padding-right:\s*40px;/, 'PR summary footer must align with the scrollable content edge')
assert.match(styles, /\.service-pr-summary-dialog\s*\{[^}]*max-height:\s*min\(92dvh,\s*900px\);/, 'PR summary dialog must leave room for three visible test items')
assert.match(styles, /\.service-pr-summary-dialog__items\s*\{[^}]*display:\s*grid;[^}]*min-height:\s*0;/, 'PR summary items box must stay inside the dialog body')
assert.match(styles, /\.service-pr-summary-dialog__items \.list-summary-dialog__item-list\s*\{[^}]*min-height:\s*0;[^}]*max-height:\s*none;/, 'PR summary item rows must scroll inside their box')
assert.match(styles, /\.service-lines[^\n]*overflow-x: auto|\.service-pr-form[^\n]*padding-bottom/, 'service form must reserve overflow/bottom clearance')
assert.match(read('app/(protected)/out-lab/page.tsx'), /permanentRedirect\('\/service-procurement\/plans\?notice=legacy-out-lab'/)
assert.equal(existsSync('lib/out-lab/actions.ts'), false, 'legacy Out Lab library must be removed')
assert.equal(existsSync('components/out-lab/OutLabTable.tsx'), false, 'legacy Out Lab components must be removed')
assert.equal(existsSync('app/api/out-lab/[id]/file/route.ts'), false, 'legacy Out Lab API must be removed')
assert.doesNotMatch(read('app/globals.css'), /\.out-lab-missing-periods/)

console.log('service procurement ui: ok')
