import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'

const read = (path: string) => readFileSync(path, 'utf8')
for (const path of [
  'app/(protected)/service-procurement/plans/page.tsx',
  'app/(protected)/service-procurement/plans/new/page.tsx',
  'app/(protected)/service-procurement/plans/[id]/page.tsx',
  'app/(protected)/service-procurement/purchase-requests/page.tsx',
  'app/(protected)/service-procurement/purchase-requests/new/page.tsx',
  'app/(protected)/service-procurement/purchase-requests/[id]/page.tsx',
]) assert.equal(existsSync(path), true, `${path} must exist`)

const shell = read('components/ui/AppShell.tsx')
assert.match(shell, /href: '\/service-procurement', label: 'งานจ้าง'/)
assert.match(shell, /href: '\/service-procurement\/plans', label: 'แผนงานจ้าง'/)
assert.match(shell, /href: '\/service-procurement\/purchase-requests', label: 'ใบ PR \(งานจ้าง\)'/)
assert.match(shell, /item\.href === '\/service-procurement\/purchase-requests'/, 'เมนูใบ PR งานจ้างต้องเลือกจำนวนแจ้งเตือนของตัวเอง')
assert.match(shell, /notificationState\.pendingServicePurchaseRequests/, 'เมนูใบ PR งานจ้างต้องแสดงจำนวนที่รอดำเนินการ')
assert.match(shell, /!serviceProcurementOpen \|\| collapsed/, 'เมื่อเมนูงานจ้างหุบหรือ sidebar ย่อ ต้องย้าย badge ไปที่หัวข้องานจ้าง')
assert.match(shell, /bench-nav__accordion-count/, 'หัวข้องานจ้างต้องมี badge สำรองเมื่อเมนูย่อยถูกซ่อน')
assert.match(shell, /const \[serviceProcurementOpen, setServiceProcurementOpen\]/, 'งานจ้างต้องมี state สำหรับยุบและขยายเมนูย่อย')
assert.match(shell, /className="bench-nav__accordion-trigger"/, 'หัวข้องานจ้างต้องเป็นปุ่ม accordion')
assert.match(shell, /aria-expanded=\{!collapsed && serviceProcurementOpen\}/, 'ปุ่มงานจ้างต้องประกาศสถานะเปิดให้ assistive technology')
assert.match(shell, /aria-controls="service-procurement-subnav"/, 'ปุ่มงานจ้างต้องเชื่อมกับรายการเมนูย่อย')
assert.match(shell, /setServiceProcurementOpen\(\(open\) => !open\)/, 'ปุ่มงานจ้างต้องสลับสถานะเมนูย่อยได้')
assert.match(shell, /bench-nav__accordion-chevron/, 'หัวข้องานจ้างต้องมี chevron แสดงสถานะ')
assert.match(shell, /bench-nav--nested/)
const plansPage = read('app/(protected)/service-procurement/plans/page.tsx')
const purchaseRequestsPage = read('app/(protected)/service-procurement/purchase-requests/page.tsx')
const serviceQueries = read('lib/service-procurement/queries.ts')
const servicePresenter = read('lib/service-procurement/presenter.ts')
assert.match(plansPage, /AutoFilterBench/)
assert.match(purchaseRequestsPage, /AutoFilterBench/)
assert.match(plansPage, /showClear=\{false\}/)
assert.match(purchaseRequestsPage, /showClear=\{false\}/)
assert.match(purchaseRequestsPage, /name: 'department'/)
assert.match(purchaseRequestsPage, /label: 'รอเจ้าหน้าที่คลังยืนยัน'/, 'ตัวกรอง PR งานจ้างต้องระบุผู้ยืนยันให้ชัดเจน')
assert.match(servicePresenter, /pending: 'รอเจ้าหน้าที่คลังยืนยัน'/, 'ป้ายสถานะ PR งานจ้างต้องระบุเจ้าหน้าที่คลังให้ชัดเจน')
assert.match(serviceQueries, /filters\.department\) query = query\.eq\('department', filters\.department\)/)
assert.doesNotMatch(plansPage, /กรองรายการ|ดูปีย้อนหลัง/)
assert.doesNotMatch(purchaseRequestsPage, /กรองรายการ|ดูปีย้อนหลัง/)
assert.doesNotMatch(plansPage, /service-procurement-tabs/)
assert.doesNotMatch(purchaseRequestsPage, /service-procurement-tabs/)
assert.doesNotMatch(read('app/globals.css'), /\.service-procurement-tabs/)
assert.match(read('app/globals.css'), /\.bench-nav__group--service/)
assert.match(read('app/globals.css'), /\.bench-nav__group--service:not\(\.is-open\) \.bench-nav--nested/, 'เมนูย่อยต้องถูกซ่อนเมื่อ accordion ปิด')
assert.match(read('app/globals.css'), /\.bench-nav__group--service\.is-open \.bench-nav__accordion-chevron/, 'chevron ต้องเปลี่ยนทิศเมื่อ accordion เปิด')
assert.match(read('app/globals.css'), /\.bench-nav__accordion-count/, 'badge ของหัวข้องานจ้างต้องจัดวางใน trigger ได้')
const autoFilter = read('components/ui/AutoFilterBench.tsx')
assert.match(autoFilter, /onChange=\{handleSelectChange\}/)
assert.doesNotMatch(autoFilter, /ตัวกรองอัปเดตอัตโนมัติ/)
assert.match(read('components/service-procurement/ServicePurchaseRequestForm.tsx'), /SELECT ITEMS/)
assert.match(read('components/service-procurement/ServicePurchaseRequestControls.tsx'), /แจ้งเตือนผ่าน LINE/)
assert.match(read('components/service-procurement/ServicePurchaseRequestHeaderEdit.tsx'), /แก้ไขข้อมูลก่อนคลังยืนยัน/)
const serviceForm = read('components/service-procurement/ServicePurchaseRequestForm.tsx')
assert.match(serviceForm, /ThaiDateInput/, 'service PR date must use the shared Thai date control')
assert.match(serviceForm, /bangkokIsoDate/, 'service PR date must use the Bangkok-local default')
assert.match(serviceForm, /StickyScroll/, 'service PR lines must use the shared scroll container')
assert.match(serviceForm, /ContractItemPicker/, 'service PR item selection must reuse the shared picker pattern')
assert.match(serviceForm, /REQUEST LINES/, 'selected service items must have their own request-lines panel')
assert.match(serviceForm, /pr-form-line-cards/, 'service PR lines must have a mobile card presentation')
assert.match(serviceForm, /pr-form-lines-table--desktop/, 'service PR lines must have an explicit desktop presentation')
assert.match(serviceForm, /aria-labelledby="service-header-title"/, 'service panels must expose heading relationships')
assert.match(serviceForm, /createServicePurchaseRequest\(formData\)/, 'service submit action must remain unchanged')
assert.match(serviceForm, /\/service-procurement\/purchase-requests/, 'service cancel route must remain unchanged')
assert.match(serviceForm, /CommitteeMemberCombobox/, 'service committee inputs must reuse the searchable PR committee control')
assert.match(serviceForm, /pr-checklist__dropzone/, 'service checklist uploads must reuse the PR dropzone presentation')
assert.match(serviceForm, /onDragOver=/, 'service checklist uploads must support drag and drop')
assert.match(serviceForm, /onDrop=/, 'service checklist uploads must accept dropped files')
assert.match(serviceForm, /formData\.set\(descriptor\.field, file/, 'dropped service files must be submitted through FormData')
assert.doesNotMatch(serviceForm, /<select required value=\{committees\.find/, 'service committee inputs must not regress to native dropdowns')
assert.match(serviceForm, /disabled=\{[^}]*!checklistComplete/, 'service PR submit must stay disabled until the checklist is complete')
const picker = read('components/pr/ContractItemPicker.tsx')
assert.match(picker, /variant\?: 'inventory' \| 'service'/, 'shared picker must expose a service presentation variant')
assert.match(picker, /manualUnitPrice\?: boolean/, 'service manual items must optionally collect a unit price')
const styles = read('app/globals.css')
assert.match(styles, /\.service-pr-form/, 'service form needs an explicit layout wrapper')
assert.match(styles, /\.service-lines[^\n]*overflow-x: auto|\.service-pr-form[^\n]*padding-bottom/, 'service form must reserve overflow/bottom clearance')
assert.match(read('app/(protected)/out-lab/page.tsx'), /permanentRedirect\('\/service-procurement\/plans\?notice=legacy-out-lab'/)
assert.equal(existsSync('lib/out-lab/actions.ts'), false, 'legacy Out Lab library must be removed')
assert.equal(existsSync('components/out-lab/OutLabTable.tsx'), false, 'legacy Out Lab components must be removed')
assert.equal(existsSync('app/api/out-lab/[id]/file/route.ts'), false, 'legacy Out Lab API must be removed')
assert.doesNotMatch(read('app/globals.css'), /\.out-lab-missing-periods/)

console.log('service procurement ui: ok')
