import assert from 'node:assert/strict'
import { existsSync, readFileSync, readdirSync } from 'node:fs'

const migrationName = readdirSync('supabase/migrations')
  .find((name) => name.endsWith('_service_plan_fiscal_year_rollover.sql'))

assert.ok(migrationName, 'service plan fiscal-year rollover migration must exist')

const migration = readFileSync(`supabase/migrations/${migrationName}`, 'utf8')
const schema = readFileSync('lib/service-procurement/schema.ts', 'utf8')
const types = readFileSync('lib/service-procurement/types.ts', 'utf8')
const queries = readFileSync('lib/service-procurement/queries.ts', 'utf8')
const actions = readFileSync('lib/service-procurement/actions.ts', 'utf8')
const plansPage = readFileSync('app/(protected)/service-procurement/plans/page.tsx', 'utf8')
const planForm = readFileSync('components/service-procurement/ServicePlanForm.tsx', 'utf8')
const newRequestPage = readFileSync('app/(protected)/service-procurement/purchase-requests/new/page.tsx', 'utf8')
const dashboardPage = readFileSync('app/(protected)/dashboard/page.tsx', 'utf8')
const executiveView = readFileSync('components/dashboard/ExecutiveDashboardView.tsx', 'utf8')
const styles = readFileSync('app/globals.css', 'utf8')

assert.match(migration, /add column if not exists rollover_source_plan_id uuid/i)
assert.match(migration, /unique[^;]+rollover_source_plan_id[^;]+fiscal_year/i)
assert.match(migration, /create table if not exists public\.service_plan_rollover_runs/i)
assert.match(migration, /alter table public\.service_plan_rollover_runs enable row level security/i)
assert.match(migration, /revoke all on table public\.service_plan_rollover_runs from public, anon, authenticated/i)
assert.match(migration, /create or replace function public\.rollover_service_procurement_plans/i)
assert.match(migration, /service_procurement_assert_actor\(p_actor_id, 'plan_admin'\)/i)
assert.match(migration, /pg_advisory_xact_lock/i)
assert.match(migration, /v_target_fiscal_year <> public\.service_procurement_fiscal_year/i)
assert.match(migration, /v_source_fiscal_year <> v_target_fiscal_year - 1/i)
assert.match(migration, /insert into public\.service_plan_test_items[\s\S]+unit_price/i)
assert.match(migration, /insert into public\.service_plan_responsibles/i)
assert.match(migration, /profile\.status = 'active'[\s\S]+profile\.deleted_at is null/i)
assert.doesNotMatch(migration, /insert into public\.service_plan_documents/i)
assert.doesNotMatch(migration, /insert into public\.service_plan_ledger/i)
assert.match(migration, /service_plan_fiscal_year_immutable/i)
assert.match(migration, /service_purchase_request_current_fiscal_year_guard/i)
assert.match(migration, /plan_row\.fiscal_year <> v_current_fiscal_year/i)
assert.match(migration, /tg_op = 'UPDATE'[\s\S]+new\.plan_id is not distinct from old\.plan_id/i)
assert.match(migration, /source_plan\.updated_at is distinct from/i)
assert.match(migration, /service_plan_rollover_touch_parent/i)
assert.match(migration, /grant execute on function public\.rollover_service_procurement_plans\(uuid, integer, integer, jsonb\) to service_role/i)
assert.match(migration, /revoke execute on function public\.rollover_service_procurement_plans\(uuid, integer, integer, jsonb\) from public, anon, authenticated/i)

assert.match(schema, /servicePlanRolloverInputSchema/)
assert.match(types, /ServicePlanRolloverReview/)
assert.match(types, /ServicePlanRolloverItem/)
assert.match(types, /ServicePlanRolloverResult/)
assert.match(queries, /getServicePlanRolloverReview/)
assert.match(queries, /listCurrentActiveServicePlansForPr/)
assert.match(queries, /getServiceProcurementDashboardSummary/)
assert.match(actions, /rolloverServicePlans/)
assert.match(actions, /revalidatePath\('\/dashboard'\)/)

assert.ok(existsSync('components/service-procurement/ServicePlanRolloverDialog.tsx'))
assert.match(plansPage, /ServicePlanRolloverDialog/)
assert.match(plansPage, /params\.rollover/)
assert.match(planForm, /mode === 'edit'[\s\S]+readOnly/)
assert.match(newRequestPage, /listCurrentActiveServicePlansForPr/)
assert.match(dashboardPage, /งานจ้างปีงบประมาณปัจจุบัน/)
assert.match(dashboardPage, /rollover=1/)
assert.match(executiveView, /serviceSourceRows/)
assert.match(executiveView, /service-procurement\/plans\?fiscalYear=/)
assert.match(executiveView, /service-procurement\/purchase-requests\?fiscalYear=/)
assert.match(executiveView, /plans\/\$\{row\.planId\}\?fiscalYear=\$\{data\.fiscalYear\}/)
assert.match(executiveView, /purchase-requests\/\$\{row\.purchaseRequestId\}\?fiscalYear=\$\{data\.fiscalYear\}/)
assert.match(styles, /\.service-plan-rollover-dialog/)
assert.match(styles, /@media \(max-width: 800px\)[\s\S]+\.service-plan-rollover-cards/)

console.log('service plan fiscal-year rollover: ok')
