import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const detail = readFileSync('app/(protected)/service-procurement/purchase-requests/[id]/page.tsx', 'utf8')
const controls = readFileSync('components/service-procurement/ServicePurchaseRequestControls.tsx', 'utf8')
const expenseEntry = readFileSync('components/service-procurement/ServicePurchaseRequestExpenseEntry.tsx', 'utf8')
const expenseLog = readFileSync('components/service-procurement/ServicePurchaseRequestExpenseLog.tsx', 'utf8')
const styles = readFileSync('app/globals.css', 'utf8')

assert.match(detail, /service-pr-detail-page/)
assert.match(detail, /service-pr-detail__hero/)
assert.match(detail, /service-procurement\/purchase-requests\/\$\{request\.id\}\/edit/)
assert.match(detail, /service-pr-detail__metrics/)
assert.match(detail, /service-pr-detail__facts/)
assert.match(detail, /formatThaiDateFull\(request\.requestedDate\)/, 'full PR detail must format requested dates as readable Thai dates')
assert.match(detail, /formatThaiDateFull\(request\.usageStartDate\)/, 'full PR detail must format the PO start date')
assert.match(detail, /formatThaiDateFull\(request\.usageEndDate\)/, 'full PR detail must format the PO end date')
assert.match(detail, /formatThaiDateFull\(event\.expenseDate\)/, 'full PR detail must format expense dates')
assert.match(detail, /service-pr-detail__items/)
assert.match(detail, /service-pr-detail__documents/)
assert.match(detail, /service-pr-detail__committees/)
assert.match(detail, /const hasPoEvidence = Boolean\(request\.poNumber\?\.trim\(\) \|\| request\.poFileName\?\.trim\(\)\)/)
assert.match(detail, /const requestedItems = request\.items\.filter\(\(item\) => item\.requestedQuantity > 0\)/)
assert.match(detail, /service-pr-detail__expenses/)
assert.match(detail, /hasPoEvidence && <section className="bench-panel service-pr-detail__section service-pr-detail__expenses"/)
assert.match(detail, /aria-label="สถานะใบ PR"/)
const expenseEntryIndex = detail.indexOf('<ServicePurchaseRequestExpenseEntry')
const expenseLogIndex = detail.indexOf('<ServicePurchaseRequestExpenseLog')
const expenseHistoryIndex = detail.indexOf('service-pr-detail__expenses')
const evidenceIndex = detail.indexOf('service-pr-detail__evidence')
const controlsIndex = detail.indexOf('<ServicePurchaseRequestControls')
assert.ok(expenseEntryIndex >= 0, 'actual expense entry should be rendered on the detail page')
assert.ok(expenseLogIndex > expenseEntryIndex, 'expense log should follow the actual expense entry')
assert.ok(expenseLogIndex < expenseHistoryIndex, 'expense history should follow the expense log')
assert.ok(expenseHistoryIndex < evidenceIndex, 'expense history should stay above documents and committees')
assert.ok(evidenceIndex < controlsIndex, 'workflow controls should stay below documents and committees')
assert.match(controls, /service-pr-workflow-actions/)
const workflowIndex = controls.indexOf('className="service-pr-actions bench-panel"')
const poHistoryIndex = controls.indexOf('className="bench-panel service-po-history"')
assert.ok(workflowIndex >= 0 && poHistoryIndex > workflowIndex, 'PO history should be rendered below the workflow section')
assert.equal(controls.includes('service-expense-list-title'), false, 'expense log should no longer be nested in workflow controls')
assert.match(controls, /formatThaiDateTimeFull/)
assert.match(controls, /<time dateTime=\{event\.createdAt\}>\{formatThaiDateTimeFull\(event\.createdAt\)\}<\/time>/)
assert.match(controls, /isEditingEphisPrNumber/)
assert.match(controls, /isEditingPoNumber/)
assert.match(controls, /readOnly=\{!isEditingEphisPrNumber\}/)
assert.match(controls, /readOnly=\{!isEditingPoNumber\}/)
assert.match(controls, /isEditingEphisPrNumber \?/) 
assert.match(controls, /isEditingPoNumber \?/) 
assert.match(styles, /\.service-pr-detail-page/)
assert.match(styles, /\.service-pr-field input:read-only/)
assert.match(styles, /\.service-pr-detail__metric--primary/)
assert.match(styles, /\.service-pr-detail__document-card/)
assert.match(styles, /\.service-pr-detail__committee-card/)
assert.match(styles, /\.service-pr-detail__items-table/)
assert.match(styles, /\.service-pr-detail__controls #service-pr-usage > \.lab-button/)
assert.match(styles, /\.service-pr-detail__controls #service-pr-usage > \.field-help/)
assert.match(styles, /\.service-pr-detail__expense-entry > \.lab-button/)
assert.match(styles, /\.service-pr-detail__expense-entry > \.field-help/)
assert.match(styles, /\.service-pr-detail__expense-log \.service-ledger-table-wrap/)
assert.match(styles, /\.service-pr-workflow-actions/)
assert.match(styles, /\.service-pr-workflow-actions\s*\{[\s\S]*padding: 16px 22px 22px;/)
assert.match(styles, /\.service-po-upload\s*\{[\s\S]*padding-bottom: 20px;/)
assert.match(styles, /\.service-pr-action-row--po\s*\{[\s\S]*padding-bottom: 20px;/)
assert.match(expenseEntry, /id="service-pr-usage"/)
assert.match(expenseEntry, /บันทึกค่าใช้จ่ายจริง/)
assert.match(expenseEntry, /hasDuplicateServiceInvoice/, 'inline expense entry must validate duplicate Invoice numbers')
assert.match(expenseEntry, /amountExceedsRequestLimit/, 'inline expense entry must detect an amount above the PR limit')
assert.match(expenseEntry, /disabled=\{pending \|\| !expenseAmount \|\| amountExceedsRequestLimit\}/, 'inline expense entry must disable save above the PR limit')
assert.match(expenseEntry, /aria-invalid=\{amountExceedsRequestLimit\}/, 'inline expense amount must be marked invalid above the PR limit')
assert.match(expenseEntry, /amount-error/, 'inline expense entry must explain the PR limit error near the amount')
assert.match(expenseEntry, /request\.requiresContract \|\| !request\.isRedCross/, 'inline expense entry must explain automatic PO closure for contract-backed and untagged PRs')
assert.doesNotMatch(expenseEntry, /Invoice <small>\(ไม่บังคับ/, 'actual expense Invoice label must not show optional-field copy')
const expenseDialog = readFileSync('components/service-procurement/ServicePurchaseRequestExpenseDialog.tsx', 'utf8')
assert.match(expenseDialog, /amountExceedsRequestLimit/, 'expense popup must detect an amount above the PR limit')
assert.match(expenseDialog, /disabled=\{pending \|\| !expenseAmount \|\| amountExceedsRequestLimit\}/, 'expense popup must disable save above the PR limit')
assert.match(expenseDialog, /amount-error/, 'expense popup must explain the PR limit error near the amount')
assert.match(expenseDialog, /request\.requiresContract \|\| !request\.isRedCross/, 'expense popup must explain automatic PO closure for contract-backed and untagged PRs')
assert.match(expenseLog, /id="service-expense-list-title"/)
assert.match(expenseLog, /formatThaiDateFull\(event\.expenseDate\)/, 'expense history must use the readable Thai date format')
assert.match(expenseLog, /รายการค่าใช้จ่ายก่อนปิด PO/)
assert.match(expenseLog, /hasDuplicateServiceInvoice/, 'expense edits must validate duplicate Invoice numbers')
assert.match(expenseLog, /service-expense-actions__group/)
assert.match(expenseLog, /service-expense-actions__edit/)
assert.match(expenseLog, /service-expense-actions__cancel/)
assert.match(expenseLog, /EditIcon/)
assert.match(expenseLog, /CancelIcon/)
assert.match(expenseLog, /CheckCircleIcon/)
assert.match(expenseLog, /aria-label="แก้ไขรายการค่าใช้จ่าย"/)
assert.match(expenseLog, /title="แก้ไขรายการค่าใช้จ่าย"/)
assert.match(expenseLog, /aria-label="ยกเลิกรายการค่าใช้จ่าย"/)
assert.match(expenseLog, /className="visually-hidden">แก้ไข<\/span>/)
assert.match(expenseLog, /className="visually-hidden">ยกเลิก<\/span>/)
assert.match(styles, /\.service-expense-actions__group/)
assert.match(styles, /\.service-expense-actions__edit/)
assert.match(styles, /\.service-expense-actions__cancel/)
assert.match(styles, /\.service-expense-actions__group svg/)
assert.match(styles, /\.service-expense-amount-input\[aria-invalid="true"\]/, 'over-limit expense amount must use the error color treatment')

console.log('service purchase request detail UI: ok')
