import Link from 'next/link'
import { notFound } from 'next/navigation'
import { requireActor } from '@/lib/auth/actor'
import { canCancelServicePurchaseRequestPo, canCloseServicePurchaseRequest, canCreateServicePurchaseRequest, canOperateServicePurchaseRequest, canRecordServicePlanExpense } from '@/lib/service-procurement/authorization'
import { getServicePurchaseRequest, getServicePlan } from '@/lib/service-procurement/queries'
import { formatBaht, serviceMethodLabel, servicePoStatusLabel, serviceRequestDisplayStatus, serviceRequestDisplayStatusLabel, serviceRequestDisplayStatusTone } from '@/lib/service-procurement/presenter'
import { ServicePurchaseRequestControls } from '@/components/service-procurement/ServicePurchaseRequestControls'

export default async function ServicePurchaseRequestDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const actor = await requireActor()
  const { id } = await params
  const request = await getServicePurchaseRequest(id)
  if (!request) notFound()
  const plan = request.planId ? (await getServicePlan(request.planId))?.plan ?? null : null
  const responsibleIds = plan?.responsibles.map((person) => person.profileId) ?? []
  const canEdit = canCreateServicePurchaseRequest(actor) && (request.requesterId === actor.id || actor.appRoles.includes('admin') || actor.appRoles.includes('head'))
  const canRecord = canRecordServicePlanExpense(actor, responsibleIds, request.requesterId)
  const displayStatus = serviceRequestDisplayStatus(request)
  const activeExpenses = request.usageEvents.filter((event) => event.kind === 'lab_expense' && event.status === 'active')

  return (
    <div className="route-stack">
      <header className="page-heading page-heading--actions"><div><Link className="back-link" href="/service-procurement/purchase-requests">← ใบ PR (งานจ้าง)</Link><p className="section-kicker">{request.documentNumber} · ปีงบ {request.fiscalYear}</p><h1>{request.planName ?? 'ไม่พบแผน'}</h1><p>{request.department} · {serviceMethodLabel(request.purchaseMethod)} · ขอวันที่ {request.requestedDate}</p></div><div className="page-heading__actions"><span className={`status-chip status-chip--${serviceRequestDisplayStatusTone(displayStatus)}`}>{serviceRequestDisplayStatusLabel(displayStatus)}</span><span className="status-chip status-chip--service">{servicePoStatusLabel(request.poStatus)}</span></div></header>
      <section className="service-pr-summary-grid"><article className="bench-panel"><small>วงเงิน PR (สำรอง)</small><strong>{formatBaht(request.requestedAmount)}</strong></article><article className="bench-panel"><small>ใช้จริงในแผน</small><strong>{formatBaht(request.status === 'closed' ? request.actualAmount : 0)}</strong></article><article className="bench-panel"><small>ผู้ขอ</small><strong>{request.requesterName}</strong></article><article className="bench-panel"><small>เลข PO</small><strong>{request.poNumber ?? 'ยังไม่มี'}</strong></article></section>
      <section className="bench-panel"><div className="bench-panel__header"><div><p className="section-kicker">REQUEST DETAILS</p><h2>รายละเอียดคำขอ</h2></div></div><dl className="service-detail-facts"><div><dt>หน่วยงานผู้ขอ</dt><dd>{request.department}</dd></div><div><dt>ประเภทงาน</dt><dd>จ้างตรวจทางห้องปฏิบัติการ</dd></div><div><dt>แผนที่อ้างอิง</dt><dd><Link className="text-link" href={`/service-procurement/plans/${request.planId}`}>{request.planName}</Link></dd></div><div><dt>ช่วงวันที่ที่จะใช้ PO นี้</dt><dd>{request.usageStartDate} – {request.usageEndDate}</dd></div><div><dt>เลข PR จาก E-Phis</dt><dd>{request.ephisPrNumber ?? 'ยังไม่ได้ระบุ'}</dd></div><div><dt>หมายเหตุ</dt><dd>{request.note ?? '—'}</dd></div></dl></section>
      {request.items.length > 0 && <section className="bench-panel"><div className="bench-panel__header"><div><p className="section-kicker">TEST ITEMS SNAPSHOT</p><h2>รายการส่งตรวจที่อ้างใน PR</h2></div><p>ข้อมูลนี้เป็น snapshot ณ วันที่สร้าง PR</p></div><div className="service-ledger-table-wrap"><table className="data-table service-pr-test-items-table"><thead><tr><th>รายการ</th><th>หน่วย</th><th className="numeric-cell">ราคาต่อหน่วย (บาท)</th><th className="numeric-cell">จำนวน</th><th className="numeric-cell">รวม</th></tr></thead><tbody>{request.items.map((item) => <tr key={item.id}><td>{item.name}</td><td>{item.unit}</td><td className="numeric-cell identifier">{item.unitPrice === null ? 'ยังไม่ระบุ' : formatBaht(item.unitPrice)}</td><td className="numeric-cell identifier">{item.requestedQuantity}</td><td className="numeric-cell identifier">{item.lineTotal === null ? '—' : formatBaht(item.lineTotal)}</td></tr>)}</tbody></table></div></section>}
      <section className="bench-panel"><div className="bench-panel__header"><div><p className="section-kicker">DOCUMENTS & COMMITTEES</p><h2>เอกสารและกรรมการ</h2></div></div><ul className="service-document-list">{request.attachments.map((file) => <li key={file.id}><span>TOR</span><a href={`/api/service-procurement/purchase-requests/${request.id}/files/${file.id}`} target="_blank" rel="noreferrer">{file.fileName}</a></li>)}{request.planDocuments.map((file) => <li key={file.id}><span>{file.kind === 'quotation' ? 'ใบเสนอราคา (ระดับแผน)' : 'หน้าสัญญา (ระดับแผน)'}</span><a href={`/api/service-procurement/plans/${request.planId}/documents/${file.id}`} target="_blank" rel="noreferrer">{file.fileName}</a></li>)}{request.poFileName && <li><span>ไฟล์ PO</span><a href={`/api/service-procurement/purchase-requests/${request.id}/files/po`} target="_blank" rel="noreferrer">{request.poFileName}</a></li>}</ul><div className="service-committee-summary"><div><h3>กำหนดราคากลางและคุณลักษณะเฉพาะ</h3><ul>{request.committees.filter((row) => row.kind === 'specification').map((row) => <li key={row.id}>{row.seat}. {row.name}</li>)}</ul></div><div><h3>ตรวจรับพัสดุ</h3><ul>{request.committees.filter((row) => row.kind === 'inspection').map((row) => <li key={row.id}>{row.seat}. {row.name}</li>)}</ul></div></div></section>
      <section className="bench-panel"><div className="bench-panel__header"><div><p className="section-kicker">EXPENSE HISTORY</p><h2>ประวัติค่าใช้จ่าย</h2></div><p>{activeExpenses.length} รายการที่ยัง active</p></div>{request.usageEvents.length === 0 ? <p className="empty-state">ยังไม่มีการบันทึกค่าใช้จ่าย</p> : <div className="service-ledger-table-wrap"><table className="data-table"><thead><tr><th>วันที่</th><th>Invoice</th><th>ยอด</th><th>สถานะ</th><th>หมายเหตุ</th><th>ผู้บันทึก</th></tr></thead><tbody>{request.usageEvents.filter((event) => event.kind === 'lab_expense').map((event) => <tr key={event.id}><td>{event.expenseDate}</td><td>{event.invoiceNumber ?? '—'}</td><td className="identifier">{formatBaht(event.amount)}</td><td>{event.status === 'active' ? 'active' : 'ยกเลิกแล้ว'}</td><td>{event.note ?? '—'}</td><td>{event.actorName ?? '—'}</td></tr>)}</tbody></table></div>}</section>
      <ServicePurchaseRequestControls request={request} canOperate={canOperateServicePurchaseRequest(actor)} canEdit={canEdit} canRecord={canRecord} canClose={canCloseServicePurchaseRequest(actor, request.requesterId, responsibleIds) && plan?.status !== 'closed'} canCancel={canCancelServicePurchaseRequestPo(actor, request.requesterId) && plan?.status !== 'closed'} />
    </div>
  )
}
